# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

apiUrl: Optional[str]
"""
URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
`https://api.ote.domrobot.com/jsonrpc/` for tests
"""

password: Optional[str]
"""
Login password of the api
"""

tan: Optional[str]
"""
Mobile-TAN to unlock account
"""

username: Optional[str]
"""
Login username of the api
"""

