# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('inwx')


class _ExportableConfig(types.ModuleType):
    @property
    def api_url(self) -> Optional[str]:
        """
        URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
        `https://api.ote.domrobot.com/jsonrpc/` for tests
        """
        return __config__.get('apiUrl')

    @property
    def password(self) -> Optional[str]:
        """
        Login password of the api
        """
        return __config__.get('password')

    @property
    def tan(self) -> Optional[str]:
        """
        Mobile-TAN to unlock account
        """
        return __config__.get('tan')

    @property
    def username(self) -> Optional[str]:
        """
        Login username of the api
        """
        return __config__.get('username')

