// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Inwx
{
    /// <summary>
    /// ## # Resource: inwx.DnssecKey
    /// 
    /// Provides a INWX DNSSEC key resource
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Inwx = Pulumi.Inwx;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var exampleCom = new Inwx.DnssecKey("exampleCom", new()
    ///     {
    ///         Algorithm = "SHA256",
    ///         Domain = "example.com",
    ///         PublicKey = "ac12c2...",
    ///     });
    /// 
    /// });
    /// ```
    /// ## Caveats
    /// 
    /// ### Nameservers
    /// 
    /// Can not be used in conjunction with INWX nameservers.
    /// 
    /// ## Import
    /// 
    /// INWX DNSSEC keys can be imported using the domain name and digest e.g.,
    /// 
    /// ```sh
    ///  $ pulumi import inwx:index/dnssecKey:DnssecKey example_com example.com/4E1243BD22C66E76C2BA9EDDC1F91394E57F9F83
    /// ```
    /// </summary>
    [InwxResourceType("inwx:index/dnssecKey:DnssecKey")]
    public partial class DnssecKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Algorithm used for the public key
        /// </summary>
        [Output("algorithm")]
        public Output<int> Algorithm { get; private set; } = null!;

        /// <summary>
        /// Computed digest for the public key
        /// </summary>
        [Output("digest")]
        public Output<string> Digest { get; private set; } = null!;

        /// <summary>
        /// Digest type
        /// </summary>
        [Output("digestType")]
        public Output<int> DigestType { get; private set; } = null!;

        /// <summary>
        /// Name of the domain
        /// </summary>
        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        /// <summary>
        /// Key flag (256=ZSK, 257=KSK)
        /// </summary>
        [Output("flag")]
        public Output<int> Flag { get; private set; } = null!;

        /// <summary>
        /// Key tag
        /// </summary>
        [Output("keyTag")]
        public Output<int> KeyTag { get; private set; } = null!;

        /// <summary>
        /// Public key of the domain
        /// </summary>
        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;

        /// <summary>
        /// DNSSEC status
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;


        /// <summary>
        /// Create a DnssecKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DnssecKey(string name, DnssecKeyArgs args, CustomResourceOptions? options = null)
            : base("inwx:index/dnssecKey:DnssecKey", name, args ?? new DnssecKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DnssecKey(string name, Input<string> id, DnssecKeyState? state = null, CustomResourceOptions? options = null)
            : base("inwx:index/dnssecKey:DnssecKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/wombelix/pulumi-inwx/releases",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DnssecKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DnssecKey Get(string name, Input<string> id, DnssecKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new DnssecKey(name, id, state, options);
        }
    }

    public sealed class DnssecKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Algorithm used for the public key
        /// </summary>
        [Input("algorithm", required: true)]
        public Input<int> Algorithm { get; set; } = null!;

        /// <summary>
        /// Name of the domain
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        /// <summary>
        /// Public key of the domain
        /// </summary>
        [Input("publicKey", required: true)]
        public Input<string> PublicKey { get; set; } = null!;

        public DnssecKeyArgs()
        {
        }
        public static new DnssecKeyArgs Empty => new DnssecKeyArgs();
    }

    public sealed class DnssecKeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Algorithm used for the public key
        /// </summary>
        [Input("algorithm")]
        public Input<int>? Algorithm { get; set; }

        /// <summary>
        /// Computed digest for the public key
        /// </summary>
        [Input("digest")]
        public Input<string>? Digest { get; set; }

        /// <summary>
        /// Digest type
        /// </summary>
        [Input("digestType")]
        public Input<int>? DigestType { get; set; }

        /// <summary>
        /// Name of the domain
        /// </summary>
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        /// <summary>
        /// Key flag (256=ZSK, 257=KSK)
        /// </summary>
        [Input("flag")]
        public Input<int>? Flag { get; set; }

        /// <summary>
        /// Key tag
        /// </summary>
        [Input("keyTag")]
        public Input<int>? KeyTag { get; set; }

        /// <summary>
        /// Public key of the domain
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        /// <summary>
        /// DNSSEC status
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public DnssecKeyState()
        {
        }
        public static new DnssecKeyState Empty => new DnssecKeyState();
    }
}
