// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Inwx
{
    /// <summary>
    /// ## Import
    /// 
    /// INWX Domains can be imported using the domain name, e.g.,
    /// 
    /// ```sh
    ///  $ pulumi import inwx:index/domain:Domain example_com "example.com"
    /// ```
    /// </summary>
    [InwxResourceType("inwx:index/domain:Domain")]
    public partial class Domain : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Contacts of the domain
        /// </summary>
        [Output("contacts")]
        public Output<Outputs.DomainContacts> Contacts { get; private set; } = null!;

        /// <summary>
        /// Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        /// </summary>
        [Output("extraData")]
        public Output<ImmutableDictionary<string, string>?> ExtraData { get; private set; } = null!;

        /// <summary>
        /// Name of the domain
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Set of nameservers of the domain. Min Items: 1
        /// </summary>
        [Output("nameservers")]
        public Output<ImmutableArray<string>> Nameservers { get; private set; } = null!;

        /// <summary>
        /// Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        /// </summary>
        [Output("period")]
        public Output<string> Period { get; private set; } = null!;

        /// <summary>
        /// Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        /// </summary>
        [Output("renewalMode")]
        public Output<string?> RenewalMode { get; private set; } = null!;

        /// <summary>
        /// Whether the domain transfer lock should be enabled. Default: `true`
        /// </summary>
        [Output("transferLock")]
        public Output<bool?> TransferLock { get; private set; } = null!;


        /// <summary>
        /// Create a Domain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Domain(string name, DomainArgs args, CustomResourceOptions? options = null)
            : base("inwx:index/domain:Domain", name, args ?? new DomainArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Domain(string name, Input<string> id, DomainState? state = null, CustomResourceOptions? options = null)
            : base("inwx:index/domain:Domain", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/wombelix/pulumi-inwx/releases",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Domain resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Domain Get(string name, Input<string> id, DomainState? state = null, CustomResourceOptions? options = null)
        {
            return new Domain(name, id, state, options);
        }
    }

    public sealed class DomainArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Contacts of the domain
        /// </summary>
        [Input("contacts", required: true)]
        public Input<Inputs.DomainContactsArgs> Contacts { get; set; } = null!;

        [Input("extraData")]
        private InputMap<string>? _extraData;

        /// <summary>
        /// Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        /// </summary>
        public InputMap<string> ExtraData
        {
            get => _extraData ?? (_extraData = new InputMap<string>());
            set => _extraData = value;
        }

        /// <summary>
        /// Name of the domain
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nameservers")]
        private InputList<string>? _nameservers;

        /// <summary>
        /// Set of nameservers of the domain. Min Items: 1
        /// </summary>
        public InputList<string> Nameservers
        {
            get => _nameservers ?? (_nameservers = new InputList<string>());
            set => _nameservers = value;
        }

        /// <summary>
        /// Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        /// </summary>
        [Input("period", required: true)]
        public Input<string> Period { get; set; } = null!;

        /// <summary>
        /// Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        /// </summary>
        [Input("renewalMode")]
        public Input<string>? RenewalMode { get; set; }

        /// <summary>
        /// Whether the domain transfer lock should be enabled. Default: `true`
        /// </summary>
        [Input("transferLock")]
        public Input<bool>? TransferLock { get; set; }

        public DomainArgs()
        {
        }
        public static new DomainArgs Empty => new DomainArgs();
    }

    public sealed class DomainState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Contacts of the domain
        /// </summary>
        [Input("contacts")]
        public Input<Inputs.DomainContactsGetArgs>? Contacts { get; set; }

        [Input("extraData")]
        private InputMap<string>? _extraData;

        /// <summary>
        /// Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        /// </summary>
        public InputMap<string> ExtraData
        {
            get => _extraData ?? (_extraData = new InputMap<string>());
            set => _extraData = value;
        }

        /// <summary>
        /// Name of the domain
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nameservers")]
        private InputList<string>? _nameservers;

        /// <summary>
        /// Set of nameservers of the domain. Min Items: 1
        /// </summary>
        public InputList<string> Nameservers
        {
            get => _nameservers ?? (_nameservers = new InputList<string>());
            set => _nameservers = value;
        }

        /// <summary>
        /// Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        /// </summary>
        [Input("period")]
        public Input<string>? Period { get; set; }

        /// <summary>
        /// Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        /// </summary>
        [Input("renewalMode")]
        public Input<string>? RenewalMode { get; set; }

        /// <summary>
        /// Whether the domain transfer lock should be enabled. Default: `true`
        /// </summary>
        [Input("transferLock")]
        public Input<bool>? TransferLock { get; set; }

        public DomainState()
        {
        }
        public static new DomainState Empty => new DomainState();
    }
}
