// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Inwx
{
    /// <summary>
    /// ## # Resource: inwx.DomainContact
    /// 
    /// Provides a INWX domain contact resource
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Inwx = Pulumi.Inwx;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var examplePerson = new Inwx.DomainContact("examplePerson", new()
    ///     {
    ///         City = "Example City",
    ///         CountryCode = "EX",
    ///         Email = "person@example.invalid",
    ///         PhoneNumber = "+00.00000000000",
    ///         PostalCode = "0",
    ///         StateProvince = "Example State",
    ///         StreetAddress = "Example Street 0",
    ///         Type = "PERSON",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// INWX domain contacts can be imported using the `id`, e.g.,
    /// 
    /// ```sh
    ///  $ pulumi import inwx:index/domainContact:DomainContact inwx_domain_contact 2147483647
    /// ```
    /// </summary>
    [InwxResourceType("inwx:index/domainContact:DomainContact")]
    public partial class DomainContact : global::Pulumi.CustomResource
    {
        /// <summary>
        /// City of the contact
        /// </summary>
        [Output("city")]
        public Output<string> City { get; private set; } = null!;

        /// <summary>
        /// Country code of the contact. Must be two characters
        /// </summary>
        [Output("countryCode")]
        public Output<string> CountryCode { get; private set; } = null!;

        /// <summary>
        /// Contact email address
        /// </summary>
        [Output("email")]
        public Output<string> Email { get; private set; } = null!;

        /// <summary>
        /// Fax number of the contact
        /// </summary>
        [Output("fax")]
        public Output<string?> Fax { get; private set; } = null!;

        /// <summary>
        /// First and lastname of the contact
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The legal name of the organization. Required for types other than person
        /// </summary>
        [Output("organization")]
        public Output<string?> Organization { get; private set; } = null!;

        /// <summary>
        /// Phone number of the contact
        /// </summary>
        [Output("phoneNumber")]
        public Output<string> PhoneNumber { get; private set; } = null!;

        /// <summary>
        /// Postal Code/Zipcode of the contact
        /// </summary>
        [Output("postalCode")]
        public Output<string> PostalCode { get; private set; } = null!;

        /// <summary>
        /// Custom description of the contact
        /// </summary>
        [Output("remarks")]
        public Output<string?> Remarks { get; private set; } = null!;

        /// <summary>
        /// State/Province name of the contact
        /// </summary>
        [Output("stateProvince")]
        public Output<string?> StateProvince { get; private set; } = null!;

        /// <summary>
        /// Street Address of the contact
        /// </summary>
        [Output("streetAddress")]
        public Output<string> StreetAddress { get; private set; } = null!;

        /// <summary>
        /// Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        /// </summary>
        [Output("whoisProtection")]
        public Output<bool?> WhoisProtection { get; private set; } = null!;


        /// <summary>
        /// Create a DomainContact resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DomainContact(string name, DomainContactArgs args, CustomResourceOptions? options = null)
            : base("inwx:index/domainContact:DomainContact", name, args ?? new DomainContactArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DomainContact(string name, Input<string> id, DomainContactState? state = null, CustomResourceOptions? options = null)
            : base("inwx:index/domainContact:DomainContact", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/wombelix/pulumi-inwx/releases",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DomainContact resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DomainContact Get(string name, Input<string> id, DomainContactState? state = null, CustomResourceOptions? options = null)
        {
            return new DomainContact(name, id, state, options);
        }
    }

    public sealed class DomainContactArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// City of the contact
        /// </summary>
        [Input("city", required: true)]
        public Input<string> City { get; set; } = null!;

        /// <summary>
        /// Country code of the contact. Must be two characters
        /// </summary>
        [Input("countryCode", required: true)]
        public Input<string> CountryCode { get; set; } = null!;

        /// <summary>
        /// Contact email address
        /// </summary>
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        /// <summary>
        /// Fax number of the contact
        /// </summary>
        [Input("fax")]
        public Input<string>? Fax { get; set; }

        /// <summary>
        /// First and lastname of the contact
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The legal name of the organization. Required for types other than person
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Phone number of the contact
        /// </summary>
        [Input("phoneNumber", required: true)]
        public Input<string> PhoneNumber { get; set; } = null!;

        /// <summary>
        /// Postal Code/Zipcode of the contact
        /// </summary>
        [Input("postalCode", required: true)]
        public Input<string> PostalCode { get; set; } = null!;

        /// <summary>
        /// Custom description of the contact
        /// </summary>
        [Input("remarks")]
        public Input<string>? Remarks { get; set; }

        /// <summary>
        /// State/Province name of the contact
        /// </summary>
        [Input("stateProvince")]
        public Input<string>? StateProvince { get; set; }

        /// <summary>
        /// Street Address of the contact
        /// </summary>
        [Input("streetAddress", required: true)]
        public Input<string> StreetAddress { get; set; } = null!;

        /// <summary>
        /// Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        /// </summary>
        [Input("whoisProtection")]
        public Input<bool>? WhoisProtection { get; set; }

        public DomainContactArgs()
        {
        }
        public static new DomainContactArgs Empty => new DomainContactArgs();
    }

    public sealed class DomainContactState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// City of the contact
        /// </summary>
        [Input("city")]
        public Input<string>? City { get; set; }

        /// <summary>
        /// Country code of the contact. Must be two characters
        /// </summary>
        [Input("countryCode")]
        public Input<string>? CountryCode { get; set; }

        /// <summary>
        /// Contact email address
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// Fax number of the contact
        /// </summary>
        [Input("fax")]
        public Input<string>? Fax { get; set; }

        /// <summary>
        /// First and lastname of the contact
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The legal name of the organization. Required for types other than person
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Phone number of the contact
        /// </summary>
        [Input("phoneNumber")]
        public Input<string>? PhoneNumber { get; set; }

        /// <summary>
        /// Postal Code/Zipcode of the contact
        /// </summary>
        [Input("postalCode")]
        public Input<string>? PostalCode { get; set; }

        /// <summary>
        /// Custom description of the contact
        /// </summary>
        [Input("remarks")]
        public Input<string>? Remarks { get; set; }

        /// <summary>
        /// State/Province name of the contact
        /// </summary>
        [Input("stateProvince")]
        public Input<string>? StateProvince { get; set; }

        /// <summary>
        /// Street Address of the contact
        /// </summary>
        [Input("streetAddress")]
        public Input<string>? StreetAddress { get; set; }

        /// <summary>
        /// Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        /// </summary>
        [Input("whoisProtection")]
        public Input<bool>? WhoisProtection { get; set; }

        public DomainContactState()
        {
        }
        public static new DomainContactState Empty => new DomainContactState();
    }
}
