// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Inwx
{
    /// <summary>
    /// ## # Resource: inwx.NameserverRecord
    /// 
    /// Provides a INWX nameserver record resource
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Inwx = Pulumi.Inwx;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var exampleComTxt1 = new Inwx.NameserverRecord("exampleComTxt1", new()
    ///     {
    ///         Content = "DNS records with terraform",
    ///         Domain = "example.com",
    ///         Type = "TXT",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// INWX nameserver records can be imported using the `id`, e.g.,
    /// 
    /// ```sh
    ///  $ pulumi import inwx:index/nameserverRecord:NameserverRecord inwx_nameserver_record example.com:2147483647
    /// ```
    /// </summary>
    [InwxResourceType("inwx:index/nameserverRecord:NameserverRecord")]
    public partial class NameserverRecord : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Content of the nameserver record
        /// </summary>
        [Output("content")]
        public Output<string> Content { get; private set; } = null!;

        /// <summary>
        /// Name of the domain
        /// </summary>
        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        /// <summary>
        /// Name of the nameserver record
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Priority of the nameserver record. Default: `0`
        /// </summary>
        [Output("prio")]
        public Output<int?> Prio { get; private set; } = null!;

        /// <summary>
        /// DNS domain id
        /// </summary>
        [Output("roId")]
        public Output<int?> RoId { get; private set; } = null!;

        /// <summary>
        /// Execute command in testing mode. Default: `false`
        /// </summary>
        [Output("testing")]
        public Output<bool?> Testing { get; private set; } = null!;

        /// <summary>
        /// TTL (time to live) of the nameserver record. Default: `3600`
        /// </summary>
        [Output("ttl")]
        public Output<int?> Ttl { get; private set; } = null!;

        /// <summary>
        /// Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
        /// `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
        /// `URI`, `URL`
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// Append the path for redirection. Default: `false`
        /// </summary>
        [Output("urlAppend")]
        public Output<bool?> UrlAppend { get; private set; } = null!;

        /// <summary>
        /// Description of the frame redirection
        /// </summary>
        [Output("urlRedirectDescription")]
        public Output<string?> UrlRedirectDescription { get; private set; } = null!;

        /// <summary>
        /// FavIcon of the frame redirection
        /// </summary>
        [Output("urlRedirectFavIcon")]
        public Output<string?> UrlRedirectFavIcon { get; private set; } = null!;

        /// <summary>
        /// Keywords of the frame redirection
        /// </summary>
        [Output("urlRedirectKeywords")]
        public Output<string?> UrlRedirectKeywords { get; private set; } = null!;

        /// <summary>
        /// Title of the frame redirection
        /// </summary>
        [Output("urlRedirectTitle")]
        public Output<string?> UrlRedirectTitle { get; private set; } = null!;

        /// <summary>
        /// Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        /// </summary>
        [Output("urlRedirectType")]
        public Output<string?> UrlRedirectType { get; private set; } = null!;


        /// <summary>
        /// Create a NameserverRecord resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NameserverRecord(string name, NameserverRecordArgs args, CustomResourceOptions? options = null)
            : base("inwx:index/nameserverRecord:NameserverRecord", name, args ?? new NameserverRecordArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NameserverRecord(string name, Input<string> id, NameserverRecordState? state = null, CustomResourceOptions? options = null)
            : base("inwx:index/nameserverRecord:NameserverRecord", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/wombelix/pulumi-inwx/releases",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NameserverRecord resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NameserverRecord Get(string name, Input<string> id, NameserverRecordState? state = null, CustomResourceOptions? options = null)
        {
            return new NameserverRecord(name, id, state, options);
        }
    }

    public sealed class NameserverRecordArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Content of the nameserver record
        /// </summary>
        [Input("content", required: true)]
        public Input<string> Content { get; set; } = null!;

        /// <summary>
        /// Name of the domain
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        /// <summary>
        /// Name of the nameserver record
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Priority of the nameserver record. Default: `0`
        /// </summary>
        [Input("prio")]
        public Input<int>? Prio { get; set; }

        /// <summary>
        /// DNS domain id
        /// </summary>
        [Input("roId")]
        public Input<int>? RoId { get; set; }

        /// <summary>
        /// Execute command in testing mode. Default: `false`
        /// </summary>
        [Input("testing")]
        public Input<bool>? Testing { get; set; }

        /// <summary>
        /// TTL (time to live) of the nameserver record. Default: `3600`
        /// </summary>
        [Input("ttl")]
        public Input<int>? Ttl { get; set; }

        /// <summary>
        /// Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
        /// `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
        /// `URI`, `URL`
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// Append the path for redirection. Default: `false`
        /// </summary>
        [Input("urlAppend")]
        public Input<bool>? UrlAppend { get; set; }

        /// <summary>
        /// Description of the frame redirection
        /// </summary>
        [Input("urlRedirectDescription")]
        public Input<string>? UrlRedirectDescription { get; set; }

        /// <summary>
        /// FavIcon of the frame redirection
        /// </summary>
        [Input("urlRedirectFavIcon")]
        public Input<string>? UrlRedirectFavIcon { get; set; }

        /// <summary>
        /// Keywords of the frame redirection
        /// </summary>
        [Input("urlRedirectKeywords")]
        public Input<string>? UrlRedirectKeywords { get; set; }

        /// <summary>
        /// Title of the frame redirection
        /// </summary>
        [Input("urlRedirectTitle")]
        public Input<string>? UrlRedirectTitle { get; set; }

        /// <summary>
        /// Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        /// </summary>
        [Input("urlRedirectType")]
        public Input<string>? UrlRedirectType { get; set; }

        public NameserverRecordArgs()
        {
        }
        public static new NameserverRecordArgs Empty => new NameserverRecordArgs();
    }

    public sealed class NameserverRecordState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Content of the nameserver record
        /// </summary>
        [Input("content")]
        public Input<string>? Content { get; set; }

        /// <summary>
        /// Name of the domain
        /// </summary>
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        /// <summary>
        /// Name of the nameserver record
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Priority of the nameserver record. Default: `0`
        /// </summary>
        [Input("prio")]
        public Input<int>? Prio { get; set; }

        /// <summary>
        /// DNS domain id
        /// </summary>
        [Input("roId")]
        public Input<int>? RoId { get; set; }

        /// <summary>
        /// Execute command in testing mode. Default: `false`
        /// </summary>
        [Input("testing")]
        public Input<bool>? Testing { get; set; }

        /// <summary>
        /// TTL (time to live) of the nameserver record. Default: `3600`
        /// </summary>
        [Input("ttl")]
        public Input<int>? Ttl { get; set; }

        /// <summary>
        /// Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
        /// `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
        /// `URI`, `URL`
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Append the path for redirection. Default: `false`
        /// </summary>
        [Input("urlAppend")]
        public Input<bool>? UrlAppend { get; set; }

        /// <summary>
        /// Description of the frame redirection
        /// </summary>
        [Input("urlRedirectDescription")]
        public Input<string>? UrlRedirectDescription { get; set; }

        /// <summary>
        /// FavIcon of the frame redirection
        /// </summary>
        [Input("urlRedirectFavIcon")]
        public Input<string>? UrlRedirectFavIcon { get; set; }

        /// <summary>
        /// Keywords of the frame redirection
        /// </summary>
        [Input("urlRedirectKeywords")]
        public Input<string>? UrlRedirectKeywords { get; set; }

        /// <summary>
        /// Title of the frame redirection
        /// </summary>
        [Input("urlRedirectTitle")]
        public Input<string>? UrlRedirectTitle { get; set; }

        /// <summary>
        /// Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        /// </summary>
        [Input("urlRedirectType")]
        public Input<string>? UrlRedirectType { get; set; }

        public NameserverRecordState()
        {
        }
        public static new NameserverRecordState Empty => new NameserverRecordState();
    }
}
