// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Inwx
{
    /// <summary>
    /// The provider type for the inwx package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [InwxResourceType("pulumi:providers:inwx")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
        /// `https://api.ote.domrobot.com/jsonrpc/` for tests
        /// </summary>
        [Output("apiUrl")]
        public Output<string?> ApiUrl { get; private set; } = null!;

        /// <summary>
        /// Login password of the api
        /// </summary>
        [Output("password")]
        public Output<string> Password { get; private set; } = null!;

        /// <summary>
        /// Mobile-TAN to unlock account
        /// </summary>
        [Output("tan")]
        public Output<string?> Tan { get; private set; } = null!;

        /// <summary>
        /// Login username of the api
        /// </summary>
        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs args, CustomResourceOptions? options = null)
            : base("inwx", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/wombelix/pulumi-inwx/releases",
                AdditionalSecretOutputs =
                {
                    "password",
                    "tan",
                    "username",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
        /// `https://api.ote.domrobot.com/jsonrpc/` for tests
        /// </summary>
        [Input("apiUrl")]
        public Input<string>? ApiUrl { get; set; }

        [Input("password", required: true)]
        private Input<string>? _password;

        /// <summary>
        /// Login password of the api
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("tan")]
        private Input<string>? _tan;

        /// <summary>
        /// Mobile-TAN to unlock account
        /// </summary>
        public Input<string>? Tan
        {
            get => _tan;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _tan = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("username", required: true)]
        private Input<string>? _username;

        /// <summary>
        /// Login username of the api
        /// </summary>
        public Input<string>? Username
        {
            get => _username;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _username = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ProviderArgs()
        {
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
