// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("inwx");

/**
 * URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
 * `https://api.ote.domrobot.com/jsonrpc/` for tests
 */
export declare const apiUrl: string | undefined;
Object.defineProperty(exports, "apiUrl", {
    get() {
        return __config.get("apiUrl");
    },
    enumerable: true,
});

/**
 * Login password of the api
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * Mobile-TAN to unlock account
 */
export declare const tan: string | undefined;
Object.defineProperty(exports, "tan", {
    get() {
        return __config.get("tan");
    },
    enumerable: true,
});

/**
 * Login username of the api
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

