// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Inwx.Outputs
{

    [OutputType]
    public sealed class DomainContacts
    {
        /// <summary>
        /// Id of the admin contact
        /// </summary>
        public readonly int Admin;
        /// <summary>
        /// Id of the billing contact
        /// </summary>
        public readonly int Billing;
        /// <summary>
        /// Id of the registrant contact
        /// </summary>
        public readonly int Registrant;
        /// <summary>
        /// Id of the tech contact
        /// </summary>
        public readonly int Tech;

        [OutputConstructor]
        private DomainContacts(
            int admin,

            int billing,

            int registrant,

            int tech)
        {
            Admin = admin;
            Billing = billing;
            Registrant = registrant;
            Tech = tech;
        }
    }
}
