// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package inwx

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wombelix/pulumi-inwx/sdk/go/inwx/internal"
)

// ## # Resource: DnssecKey
//
// # Provides a INWX DNSSEC key resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/wombelix/pulumi-inwx/sdk/go/inwx"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := inwx.NewDnssecKey(ctx, "exampleCom", &inwx.DnssecKeyArgs{
//				Algorithm: pulumi.Int("SHA256"),
//				Domain:    pulumi.String("example.com"),
//				PublicKey: pulumi.String("ac12c2..."),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// ## Caveats
//
// ### Nameservers
//
// Can not be used in conjunction with INWX nameservers.
//
// ## Import
//
// INWX DNSSEC keys can be imported using the domain name and digest e.g.,
//
// ```sh
//
//	$ pulumi import inwx:index/dnssecKey:DnssecKey example_com example.com/4E1243BD22C66E76C2BA9EDDC1F91394E57F9F83
//
// ```
type DnssecKey struct {
	pulumi.CustomResourceState

	// Algorithm used for the public key
	Algorithm pulumi.IntOutput `pulumi:"algorithm"`
	// Computed digest for the public key
	Digest pulumi.StringOutput `pulumi:"digest"`
	// Digest type
	DigestType pulumi.IntOutput `pulumi:"digestType"`
	// Name of the domain
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Key flag (256=ZSK, 257=KSK)
	Flag pulumi.IntOutput `pulumi:"flag"`
	// Key tag
	KeyTag pulumi.IntOutput `pulumi:"keyTag"`
	// Public key of the domain
	PublicKey pulumi.StringOutput `pulumi:"publicKey"`
	// DNSSEC status
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewDnssecKey registers a new resource with the given unique name, arguments, and options.
func NewDnssecKey(ctx *pulumi.Context,
	name string, args *DnssecKeyArgs, opts ...pulumi.ResourceOption) (*DnssecKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Algorithm == nil {
		return nil, errors.New("invalid value for required argument 'Algorithm'")
	}
	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.PublicKey == nil {
		return nil, errors.New("invalid value for required argument 'PublicKey'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DnssecKey
	err := ctx.RegisterResource("inwx:index/dnssecKey:DnssecKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDnssecKey gets an existing DnssecKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDnssecKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DnssecKeyState, opts ...pulumi.ResourceOption) (*DnssecKey, error) {
	var resource DnssecKey
	err := ctx.ReadResource("inwx:index/dnssecKey:DnssecKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DnssecKey resources.
type dnssecKeyState struct {
	// Algorithm used for the public key
	Algorithm *int `pulumi:"algorithm"`
	// Computed digest for the public key
	Digest *string `pulumi:"digest"`
	// Digest type
	DigestType *int `pulumi:"digestType"`
	// Name of the domain
	Domain *string `pulumi:"domain"`
	// Key flag (256=ZSK, 257=KSK)
	Flag *int `pulumi:"flag"`
	// Key tag
	KeyTag *int `pulumi:"keyTag"`
	// Public key of the domain
	PublicKey *string `pulumi:"publicKey"`
	// DNSSEC status
	Status *string `pulumi:"status"`
}

type DnssecKeyState struct {
	// Algorithm used for the public key
	Algorithm pulumi.IntPtrInput
	// Computed digest for the public key
	Digest pulumi.StringPtrInput
	// Digest type
	DigestType pulumi.IntPtrInput
	// Name of the domain
	Domain pulumi.StringPtrInput
	// Key flag (256=ZSK, 257=KSK)
	Flag pulumi.IntPtrInput
	// Key tag
	KeyTag pulumi.IntPtrInput
	// Public key of the domain
	PublicKey pulumi.StringPtrInput
	// DNSSEC status
	Status pulumi.StringPtrInput
}

func (DnssecKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnssecKeyState)(nil)).Elem()
}

type dnssecKeyArgs struct {
	// Algorithm used for the public key
	Algorithm int `pulumi:"algorithm"`
	// Name of the domain
	Domain string `pulumi:"domain"`
	// Public key of the domain
	PublicKey string `pulumi:"publicKey"`
}

// The set of arguments for constructing a DnssecKey resource.
type DnssecKeyArgs struct {
	// Algorithm used for the public key
	Algorithm pulumi.IntInput
	// Name of the domain
	Domain pulumi.StringInput
	// Public key of the domain
	PublicKey pulumi.StringInput
}

func (DnssecKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnssecKeyArgs)(nil)).Elem()
}

type DnssecKeyInput interface {
	pulumi.Input

	ToDnssecKeyOutput() DnssecKeyOutput
	ToDnssecKeyOutputWithContext(ctx context.Context) DnssecKeyOutput
}

func (*DnssecKey) ElementType() reflect.Type {
	return reflect.TypeOf((**DnssecKey)(nil)).Elem()
}

func (i *DnssecKey) ToDnssecKeyOutput() DnssecKeyOutput {
	return i.ToDnssecKeyOutputWithContext(context.Background())
}

func (i *DnssecKey) ToDnssecKeyOutputWithContext(ctx context.Context) DnssecKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnssecKeyOutput)
}

// DnssecKeyArrayInput is an input type that accepts DnssecKeyArray and DnssecKeyArrayOutput values.
// You can construct a concrete instance of `DnssecKeyArrayInput` via:
//
//	DnssecKeyArray{ DnssecKeyArgs{...} }
type DnssecKeyArrayInput interface {
	pulumi.Input

	ToDnssecKeyArrayOutput() DnssecKeyArrayOutput
	ToDnssecKeyArrayOutputWithContext(context.Context) DnssecKeyArrayOutput
}

type DnssecKeyArray []DnssecKeyInput

func (DnssecKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DnssecKey)(nil)).Elem()
}

func (i DnssecKeyArray) ToDnssecKeyArrayOutput() DnssecKeyArrayOutput {
	return i.ToDnssecKeyArrayOutputWithContext(context.Background())
}

func (i DnssecKeyArray) ToDnssecKeyArrayOutputWithContext(ctx context.Context) DnssecKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnssecKeyArrayOutput)
}

// DnssecKeyMapInput is an input type that accepts DnssecKeyMap and DnssecKeyMapOutput values.
// You can construct a concrete instance of `DnssecKeyMapInput` via:
//
//	DnssecKeyMap{ "key": DnssecKeyArgs{...} }
type DnssecKeyMapInput interface {
	pulumi.Input

	ToDnssecKeyMapOutput() DnssecKeyMapOutput
	ToDnssecKeyMapOutputWithContext(context.Context) DnssecKeyMapOutput
}

type DnssecKeyMap map[string]DnssecKeyInput

func (DnssecKeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DnssecKey)(nil)).Elem()
}

func (i DnssecKeyMap) ToDnssecKeyMapOutput() DnssecKeyMapOutput {
	return i.ToDnssecKeyMapOutputWithContext(context.Background())
}

func (i DnssecKeyMap) ToDnssecKeyMapOutputWithContext(ctx context.Context) DnssecKeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnssecKeyMapOutput)
}

type DnssecKeyOutput struct{ *pulumi.OutputState }

func (DnssecKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DnssecKey)(nil)).Elem()
}

func (o DnssecKeyOutput) ToDnssecKeyOutput() DnssecKeyOutput {
	return o
}

func (o DnssecKeyOutput) ToDnssecKeyOutputWithContext(ctx context.Context) DnssecKeyOutput {
	return o
}

// Algorithm used for the public key
func (o DnssecKeyOutput) Algorithm() pulumi.IntOutput {
	return o.ApplyT(func(v *DnssecKey) pulumi.IntOutput { return v.Algorithm }).(pulumi.IntOutput)
}

// Computed digest for the public key
func (o DnssecKeyOutput) Digest() pulumi.StringOutput {
	return o.ApplyT(func(v *DnssecKey) pulumi.StringOutput { return v.Digest }).(pulumi.StringOutput)
}

// Digest type
func (o DnssecKeyOutput) DigestType() pulumi.IntOutput {
	return o.ApplyT(func(v *DnssecKey) pulumi.IntOutput { return v.DigestType }).(pulumi.IntOutput)
}

// Name of the domain
func (o DnssecKeyOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *DnssecKey) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Key flag (256=ZSK, 257=KSK)
func (o DnssecKeyOutput) Flag() pulumi.IntOutput {
	return o.ApplyT(func(v *DnssecKey) pulumi.IntOutput { return v.Flag }).(pulumi.IntOutput)
}

// Key tag
func (o DnssecKeyOutput) KeyTag() pulumi.IntOutput {
	return o.ApplyT(func(v *DnssecKey) pulumi.IntOutput { return v.KeyTag }).(pulumi.IntOutput)
}

// Public key of the domain
func (o DnssecKeyOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *DnssecKey) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

// DNSSEC status
func (o DnssecKeyOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *DnssecKey) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

type DnssecKeyArrayOutput struct{ *pulumi.OutputState }

func (DnssecKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DnssecKey)(nil)).Elem()
}

func (o DnssecKeyArrayOutput) ToDnssecKeyArrayOutput() DnssecKeyArrayOutput {
	return o
}

func (o DnssecKeyArrayOutput) ToDnssecKeyArrayOutputWithContext(ctx context.Context) DnssecKeyArrayOutput {
	return o
}

func (o DnssecKeyArrayOutput) Index(i pulumi.IntInput) DnssecKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DnssecKey {
		return vs[0].([]*DnssecKey)[vs[1].(int)]
	}).(DnssecKeyOutput)
}

type DnssecKeyMapOutput struct{ *pulumi.OutputState }

func (DnssecKeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DnssecKey)(nil)).Elem()
}

func (o DnssecKeyMapOutput) ToDnssecKeyMapOutput() DnssecKeyMapOutput {
	return o
}

func (o DnssecKeyMapOutput) ToDnssecKeyMapOutputWithContext(ctx context.Context) DnssecKeyMapOutput {
	return o
}

func (o DnssecKeyMapOutput) MapIndex(k pulumi.StringInput) DnssecKeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DnssecKey {
		return vs[0].(map[string]*DnssecKey)[vs[1].(string)]
	}).(DnssecKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DnssecKeyInput)(nil)).Elem(), &DnssecKey{})
	pulumi.RegisterInputType(reflect.TypeOf((*DnssecKeyArrayInput)(nil)).Elem(), DnssecKeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DnssecKeyMapInput)(nil)).Elem(), DnssecKeyMap{})
	pulumi.RegisterOutputType(DnssecKeyOutput{})
	pulumi.RegisterOutputType(DnssecKeyArrayOutput{})
	pulumi.RegisterOutputType(DnssecKeyMapOutput{})
}
