// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package inwx

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wombelix/pulumi-inwx/sdk/go/inwx/internal"
)

// ## # Resource: DomainContact
//
// # Provides a INWX domain contact resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/wombelix/pulumi-inwx/sdk/go/inwx"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := inwx.NewDomainContact(ctx, "examplePerson", &inwx.DomainContactArgs{
//				City:          pulumi.String("Example City"),
//				CountryCode:   pulumi.String("EX"),
//				Email:         pulumi.String("person@example.invalid"),
//				PhoneNumber:   pulumi.String("+00.00000000000"),
//				PostalCode:    pulumi.String("0"),
//				StateProvince: pulumi.String("Example State"),
//				StreetAddress: pulumi.String("Example Street 0"),
//				Type:          pulumi.String("PERSON"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// INWX domain contacts can be imported using the `id`, e.g.,
//
// ```sh
//
//	$ pulumi import inwx:index/domainContact:DomainContact inwx_domain_contact 2147483647
//
// ```
type DomainContact struct {
	pulumi.CustomResourceState

	// City of the contact
	City pulumi.StringOutput `pulumi:"city"`
	// Country code of the contact. Must be two characters
	CountryCode pulumi.StringOutput `pulumi:"countryCode"`
	// Contact email address
	Email pulumi.StringOutput `pulumi:"email"`
	// Fax number of the contact
	Fax pulumi.StringPtrOutput `pulumi:"fax"`
	// First and lastname of the contact
	Name pulumi.StringOutput `pulumi:"name"`
	// The legal name of the organization. Required for types other than person
	Organization pulumi.StringPtrOutput `pulumi:"organization"`
	// Phone number of the contact
	PhoneNumber pulumi.StringOutput `pulumi:"phoneNumber"`
	// Postal Code/Zipcode of the contact
	PostalCode pulumi.StringOutput `pulumi:"postalCode"`
	// Custom description of the contact
	Remarks pulumi.StringPtrOutput `pulumi:"remarks"`
	// State/Province name of the contact
	StateProvince pulumi.StringPtrOutput `pulumi:"stateProvince"`
	// Street Address of the contact
	StreetAddress pulumi.StringOutput `pulumi:"streetAddress"`
	// Type of contact. One of: `ORG`, `PERSON`, `ROLE`
	Type pulumi.StringOutput `pulumi:"type"`
	// Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
	WhoisProtection pulumi.BoolPtrOutput `pulumi:"whoisProtection"`
}

// NewDomainContact registers a new resource with the given unique name, arguments, and options.
func NewDomainContact(ctx *pulumi.Context,
	name string, args *DomainContactArgs, opts ...pulumi.ResourceOption) (*DomainContact, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.City == nil {
		return nil, errors.New("invalid value for required argument 'City'")
	}
	if args.CountryCode == nil {
		return nil, errors.New("invalid value for required argument 'CountryCode'")
	}
	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	if args.PhoneNumber == nil {
		return nil, errors.New("invalid value for required argument 'PhoneNumber'")
	}
	if args.PostalCode == nil {
		return nil, errors.New("invalid value for required argument 'PostalCode'")
	}
	if args.StreetAddress == nil {
		return nil, errors.New("invalid value for required argument 'StreetAddress'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DomainContact
	err := ctx.RegisterResource("inwx:index/domainContact:DomainContact", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomainContact gets an existing DomainContact resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomainContact(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainContactState, opts ...pulumi.ResourceOption) (*DomainContact, error) {
	var resource DomainContact
	err := ctx.ReadResource("inwx:index/domainContact:DomainContact", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DomainContact resources.
type domainContactState struct {
	// City of the contact
	City *string `pulumi:"city"`
	// Country code of the contact. Must be two characters
	CountryCode *string `pulumi:"countryCode"`
	// Contact email address
	Email *string `pulumi:"email"`
	// Fax number of the contact
	Fax *string `pulumi:"fax"`
	// First and lastname of the contact
	Name *string `pulumi:"name"`
	// The legal name of the organization. Required for types other than person
	Organization *string `pulumi:"organization"`
	// Phone number of the contact
	PhoneNumber *string `pulumi:"phoneNumber"`
	// Postal Code/Zipcode of the contact
	PostalCode *string `pulumi:"postalCode"`
	// Custom description of the contact
	Remarks *string `pulumi:"remarks"`
	// State/Province name of the contact
	StateProvince *string `pulumi:"stateProvince"`
	// Street Address of the contact
	StreetAddress *string `pulumi:"streetAddress"`
	// Type of contact. One of: `ORG`, `PERSON`, `ROLE`
	Type *string `pulumi:"type"`
	// Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
	WhoisProtection *bool `pulumi:"whoisProtection"`
}

type DomainContactState struct {
	// City of the contact
	City pulumi.StringPtrInput
	// Country code of the contact. Must be two characters
	CountryCode pulumi.StringPtrInput
	// Contact email address
	Email pulumi.StringPtrInput
	// Fax number of the contact
	Fax pulumi.StringPtrInput
	// First and lastname of the contact
	Name pulumi.StringPtrInput
	// The legal name of the organization. Required for types other than person
	Organization pulumi.StringPtrInput
	// Phone number of the contact
	PhoneNumber pulumi.StringPtrInput
	// Postal Code/Zipcode of the contact
	PostalCode pulumi.StringPtrInput
	// Custom description of the contact
	Remarks pulumi.StringPtrInput
	// State/Province name of the contact
	StateProvince pulumi.StringPtrInput
	// Street Address of the contact
	StreetAddress pulumi.StringPtrInput
	// Type of contact. One of: `ORG`, `PERSON`, `ROLE`
	Type pulumi.StringPtrInput
	// Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
	WhoisProtection pulumi.BoolPtrInput
}

func (DomainContactState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainContactState)(nil)).Elem()
}

type domainContactArgs struct {
	// City of the contact
	City string `pulumi:"city"`
	// Country code of the contact. Must be two characters
	CountryCode string `pulumi:"countryCode"`
	// Contact email address
	Email string `pulumi:"email"`
	// Fax number of the contact
	Fax *string `pulumi:"fax"`
	// First and lastname of the contact
	Name *string `pulumi:"name"`
	// The legal name of the organization. Required for types other than person
	Organization *string `pulumi:"organization"`
	// Phone number of the contact
	PhoneNumber string `pulumi:"phoneNumber"`
	// Postal Code/Zipcode of the contact
	PostalCode string `pulumi:"postalCode"`
	// Custom description of the contact
	Remarks *string `pulumi:"remarks"`
	// State/Province name of the contact
	StateProvince *string `pulumi:"stateProvince"`
	// Street Address of the contact
	StreetAddress string `pulumi:"streetAddress"`
	// Type of contact. One of: `ORG`, `PERSON`, `ROLE`
	Type string `pulumi:"type"`
	// Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
	WhoisProtection *bool `pulumi:"whoisProtection"`
}

// The set of arguments for constructing a DomainContact resource.
type DomainContactArgs struct {
	// City of the contact
	City pulumi.StringInput
	// Country code of the contact. Must be two characters
	CountryCode pulumi.StringInput
	// Contact email address
	Email pulumi.StringInput
	// Fax number of the contact
	Fax pulumi.StringPtrInput
	// First and lastname of the contact
	Name pulumi.StringPtrInput
	// The legal name of the organization. Required for types other than person
	Organization pulumi.StringPtrInput
	// Phone number of the contact
	PhoneNumber pulumi.StringInput
	// Postal Code/Zipcode of the contact
	PostalCode pulumi.StringInput
	// Custom description of the contact
	Remarks pulumi.StringPtrInput
	// State/Province name of the contact
	StateProvince pulumi.StringPtrInput
	// Street Address of the contact
	StreetAddress pulumi.StringInput
	// Type of contact. One of: `ORG`, `PERSON`, `ROLE`
	Type pulumi.StringInput
	// Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
	WhoisProtection pulumi.BoolPtrInput
}

func (DomainContactArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainContactArgs)(nil)).Elem()
}

type DomainContactInput interface {
	pulumi.Input

	ToDomainContactOutput() DomainContactOutput
	ToDomainContactOutputWithContext(ctx context.Context) DomainContactOutput
}

func (*DomainContact) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainContact)(nil)).Elem()
}

func (i *DomainContact) ToDomainContactOutput() DomainContactOutput {
	return i.ToDomainContactOutputWithContext(context.Background())
}

func (i *DomainContact) ToDomainContactOutputWithContext(ctx context.Context) DomainContactOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainContactOutput)
}

// DomainContactArrayInput is an input type that accepts DomainContactArray and DomainContactArrayOutput values.
// You can construct a concrete instance of `DomainContactArrayInput` via:
//
//	DomainContactArray{ DomainContactArgs{...} }
type DomainContactArrayInput interface {
	pulumi.Input

	ToDomainContactArrayOutput() DomainContactArrayOutput
	ToDomainContactArrayOutputWithContext(context.Context) DomainContactArrayOutput
}

type DomainContactArray []DomainContactInput

func (DomainContactArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainContact)(nil)).Elem()
}

func (i DomainContactArray) ToDomainContactArrayOutput() DomainContactArrayOutput {
	return i.ToDomainContactArrayOutputWithContext(context.Background())
}

func (i DomainContactArray) ToDomainContactArrayOutputWithContext(ctx context.Context) DomainContactArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainContactArrayOutput)
}

// DomainContactMapInput is an input type that accepts DomainContactMap and DomainContactMapOutput values.
// You can construct a concrete instance of `DomainContactMapInput` via:
//
//	DomainContactMap{ "key": DomainContactArgs{...} }
type DomainContactMapInput interface {
	pulumi.Input

	ToDomainContactMapOutput() DomainContactMapOutput
	ToDomainContactMapOutputWithContext(context.Context) DomainContactMapOutput
}

type DomainContactMap map[string]DomainContactInput

func (DomainContactMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainContact)(nil)).Elem()
}

func (i DomainContactMap) ToDomainContactMapOutput() DomainContactMapOutput {
	return i.ToDomainContactMapOutputWithContext(context.Background())
}

func (i DomainContactMap) ToDomainContactMapOutputWithContext(ctx context.Context) DomainContactMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainContactMapOutput)
}

type DomainContactOutput struct{ *pulumi.OutputState }

func (DomainContactOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainContact)(nil)).Elem()
}

func (o DomainContactOutput) ToDomainContactOutput() DomainContactOutput {
	return o
}

func (o DomainContactOutput) ToDomainContactOutputWithContext(ctx context.Context) DomainContactOutput {
	return o
}

// City of the contact
func (o DomainContactOutput) City() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringOutput { return v.City }).(pulumi.StringOutput)
}

// Country code of the contact. Must be two characters
func (o DomainContactOutput) CountryCode() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringOutput { return v.CountryCode }).(pulumi.StringOutput)
}

// Contact email address
func (o DomainContactOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// Fax number of the contact
func (o DomainContactOutput) Fax() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringPtrOutput { return v.Fax }).(pulumi.StringPtrOutput)
}

// First and lastname of the contact
func (o DomainContactOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The legal name of the organization. Required for types other than person
func (o DomainContactOutput) Organization() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringPtrOutput { return v.Organization }).(pulumi.StringPtrOutput)
}

// Phone number of the contact
func (o DomainContactOutput) PhoneNumber() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringOutput { return v.PhoneNumber }).(pulumi.StringOutput)
}

// Postal Code/Zipcode of the contact
func (o DomainContactOutput) PostalCode() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringOutput { return v.PostalCode }).(pulumi.StringOutput)
}

// Custom description of the contact
func (o DomainContactOutput) Remarks() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringPtrOutput { return v.Remarks }).(pulumi.StringPtrOutput)
}

// State/Province name of the contact
func (o DomainContactOutput) StateProvince() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringPtrOutput { return v.StateProvince }).(pulumi.StringPtrOutput)
}

// Street Address of the contact
func (o DomainContactOutput) StreetAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringOutput { return v.StreetAddress }).(pulumi.StringOutput)
}

// Type of contact. One of: `ORG`, `PERSON`, `ROLE`
func (o DomainContactOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
func (o DomainContactOutput) WhoisProtection() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainContact) pulumi.BoolPtrOutput { return v.WhoisProtection }).(pulumi.BoolPtrOutput)
}

type DomainContactArrayOutput struct{ *pulumi.OutputState }

func (DomainContactArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainContact)(nil)).Elem()
}

func (o DomainContactArrayOutput) ToDomainContactArrayOutput() DomainContactArrayOutput {
	return o
}

func (o DomainContactArrayOutput) ToDomainContactArrayOutputWithContext(ctx context.Context) DomainContactArrayOutput {
	return o
}

func (o DomainContactArrayOutput) Index(i pulumi.IntInput) DomainContactOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DomainContact {
		return vs[0].([]*DomainContact)[vs[1].(int)]
	}).(DomainContactOutput)
}

type DomainContactMapOutput struct{ *pulumi.OutputState }

func (DomainContactMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainContact)(nil)).Elem()
}

func (o DomainContactMapOutput) ToDomainContactMapOutput() DomainContactMapOutput {
	return o
}

func (o DomainContactMapOutput) ToDomainContactMapOutputWithContext(ctx context.Context) DomainContactMapOutput {
	return o
}

func (o DomainContactMapOutput) MapIndex(k pulumi.StringInput) DomainContactOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DomainContact {
		return vs[0].(map[string]*DomainContact)[vs[1].(string)]
	}).(DomainContactOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainContactInput)(nil)).Elem(), &DomainContact{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainContactArrayInput)(nil)).Elem(), DomainContactArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainContactMapInput)(nil)).Elem(), DomainContactMap{})
	pulumi.RegisterOutputType(DomainContactOutput{})
	pulumi.RegisterOutputType(DomainContactArrayOutput{})
	pulumi.RegisterOutputType(DomainContactMapOutput{})
}
