// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package inwx

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wombelix/pulumi-inwx/sdk/go/inwx/internal"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "inwx:index/dnssecKey:DnssecKey":
		r = &DnssecKey{}
	case "inwx:index/domain:Domain":
		r = &Domain{}
	case "inwx:index/domainContact:DomainContact":
		r = &DomainContact{}
	case "inwx:index/nameserverRecord:NameserverRecord":
		r = &NameserverRecord{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:inwx" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"inwx",
		"index/dnssecKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"inwx",
		"index/domain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"inwx",
		"index/domainContact",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"inwx",
		"index/nameserverRecord",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"inwx",
		&pkg{version},
	)
}
