// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package inwx

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wombelix/pulumi-inwx/sdk/go/inwx/internal"
)

// ## # Resource: NameserverRecord
//
// # Provides a INWX nameserver record resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/wombelix/pulumi-inwx/sdk/go/inwx"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := inwx.NewNameserverRecord(ctx, "exampleComTxt1", &inwx.NameserverRecordArgs{
//				Content: pulumi.String("DNS records with terraform"),
//				Domain:  pulumi.String("example.com"),
//				Type:    pulumi.String("TXT"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// INWX nameserver records can be imported using the `id`, e.g.,
//
// ```sh
//
//	$ pulumi import inwx:index/nameserverRecord:NameserverRecord inwx_nameserver_record example.com:2147483647
//
// ```
type NameserverRecord struct {
	pulumi.CustomResourceState

	// Content of the nameserver record
	Content pulumi.StringOutput `pulumi:"content"`
	// Name of the domain
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Name of the nameserver record
	Name pulumi.StringOutput `pulumi:"name"`
	// Priority of the nameserver record. Default: `0`
	Prio pulumi.IntPtrOutput `pulumi:"prio"`
	// DNS domain id
	RoId pulumi.IntPtrOutput `pulumi:"roId"`
	// Execute command in testing mode. Default: `false`
	Testing pulumi.BoolPtrOutput `pulumi:"testing"`
	// TTL (time to live) of the nameserver record. Default: `3600`
	Ttl pulumi.IntPtrOutput `pulumi:"ttl"`
	// Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`,
	// `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
	// `URI`, `URL`
	Type pulumi.StringOutput `pulumi:"type"`
	// Append the path for redirection. Default: `false`
	UrlAppend pulumi.BoolPtrOutput `pulumi:"urlAppend"`
	// Description of the frame redirection
	UrlRedirectDescription pulumi.StringPtrOutput `pulumi:"urlRedirectDescription"`
	// FavIcon of the frame redirection
	UrlRedirectFavIcon pulumi.StringPtrOutput `pulumi:"urlRedirectFavIcon"`
	// Keywords of the frame redirection
	UrlRedirectKeywords pulumi.StringPtrOutput `pulumi:"urlRedirectKeywords"`
	// Title of the frame redirection
	UrlRedirectTitle pulumi.StringPtrOutput `pulumi:"urlRedirectTitle"`
	// Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
	UrlRedirectType pulumi.StringPtrOutput `pulumi:"urlRedirectType"`
}

// NewNameserverRecord registers a new resource with the given unique name, arguments, and options.
func NewNameserverRecord(ctx *pulumi.Context,
	name string, args *NameserverRecordArgs, opts ...pulumi.ResourceOption) (*NameserverRecord, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Content == nil {
		return nil, errors.New("invalid value for required argument 'Content'")
	}
	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NameserverRecord
	err := ctx.RegisterResource("inwx:index/nameserverRecord:NameserverRecord", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNameserverRecord gets an existing NameserverRecord resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNameserverRecord(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NameserverRecordState, opts ...pulumi.ResourceOption) (*NameserverRecord, error) {
	var resource NameserverRecord
	err := ctx.ReadResource("inwx:index/nameserverRecord:NameserverRecord", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NameserverRecord resources.
type nameserverRecordState struct {
	// Content of the nameserver record
	Content *string `pulumi:"content"`
	// Name of the domain
	Domain *string `pulumi:"domain"`
	// Name of the nameserver record
	Name *string `pulumi:"name"`
	// Priority of the nameserver record. Default: `0`
	Prio *int `pulumi:"prio"`
	// DNS domain id
	RoId *int `pulumi:"roId"`
	// Execute command in testing mode. Default: `false`
	Testing *bool `pulumi:"testing"`
	// TTL (time to live) of the nameserver record. Default: `3600`
	Ttl *int `pulumi:"ttl"`
	// Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`,
	// `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
	// `URI`, `URL`
	Type *string `pulumi:"type"`
	// Append the path for redirection. Default: `false`
	UrlAppend *bool `pulumi:"urlAppend"`
	// Description of the frame redirection
	UrlRedirectDescription *string `pulumi:"urlRedirectDescription"`
	// FavIcon of the frame redirection
	UrlRedirectFavIcon *string `pulumi:"urlRedirectFavIcon"`
	// Keywords of the frame redirection
	UrlRedirectKeywords *string `pulumi:"urlRedirectKeywords"`
	// Title of the frame redirection
	UrlRedirectTitle *string `pulumi:"urlRedirectTitle"`
	// Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
	UrlRedirectType *string `pulumi:"urlRedirectType"`
}

type NameserverRecordState struct {
	// Content of the nameserver record
	Content pulumi.StringPtrInput
	// Name of the domain
	Domain pulumi.StringPtrInput
	// Name of the nameserver record
	Name pulumi.StringPtrInput
	// Priority of the nameserver record. Default: `0`
	Prio pulumi.IntPtrInput
	// DNS domain id
	RoId pulumi.IntPtrInput
	// Execute command in testing mode. Default: `false`
	Testing pulumi.BoolPtrInput
	// TTL (time to live) of the nameserver record. Default: `3600`
	Ttl pulumi.IntPtrInput
	// Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`,
	// `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
	// `URI`, `URL`
	Type pulumi.StringPtrInput
	// Append the path for redirection. Default: `false`
	UrlAppend pulumi.BoolPtrInput
	// Description of the frame redirection
	UrlRedirectDescription pulumi.StringPtrInput
	// FavIcon of the frame redirection
	UrlRedirectFavIcon pulumi.StringPtrInput
	// Keywords of the frame redirection
	UrlRedirectKeywords pulumi.StringPtrInput
	// Title of the frame redirection
	UrlRedirectTitle pulumi.StringPtrInput
	// Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
	UrlRedirectType pulumi.StringPtrInput
}

func (NameserverRecordState) ElementType() reflect.Type {
	return reflect.TypeOf((*nameserverRecordState)(nil)).Elem()
}

type nameserverRecordArgs struct {
	// Content of the nameserver record
	Content string `pulumi:"content"`
	// Name of the domain
	Domain string `pulumi:"domain"`
	// Name of the nameserver record
	Name *string `pulumi:"name"`
	// Priority of the nameserver record. Default: `0`
	Prio *int `pulumi:"prio"`
	// DNS domain id
	RoId *int `pulumi:"roId"`
	// Execute command in testing mode. Default: `false`
	Testing *bool `pulumi:"testing"`
	// TTL (time to live) of the nameserver record. Default: `3600`
	Ttl *int `pulumi:"ttl"`
	// Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`,
	// `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
	// `URI`, `URL`
	Type string `pulumi:"type"`
	// Append the path for redirection. Default: `false`
	UrlAppend *bool `pulumi:"urlAppend"`
	// Description of the frame redirection
	UrlRedirectDescription *string `pulumi:"urlRedirectDescription"`
	// FavIcon of the frame redirection
	UrlRedirectFavIcon *string `pulumi:"urlRedirectFavIcon"`
	// Keywords of the frame redirection
	UrlRedirectKeywords *string `pulumi:"urlRedirectKeywords"`
	// Title of the frame redirection
	UrlRedirectTitle *string `pulumi:"urlRedirectTitle"`
	// Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
	UrlRedirectType *string `pulumi:"urlRedirectType"`
}

// The set of arguments for constructing a NameserverRecord resource.
type NameserverRecordArgs struct {
	// Content of the nameserver record
	Content pulumi.StringInput
	// Name of the domain
	Domain pulumi.StringInput
	// Name of the nameserver record
	Name pulumi.StringPtrInput
	// Priority of the nameserver record. Default: `0`
	Prio pulumi.IntPtrInput
	// DNS domain id
	RoId pulumi.IntPtrInput
	// Execute command in testing mode. Default: `false`
	Testing pulumi.BoolPtrInput
	// TTL (time to live) of the nameserver record. Default: `3600`
	Ttl pulumi.IntPtrInput
	// Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`,
	// `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
	// `URI`, `URL`
	Type pulumi.StringInput
	// Append the path for redirection. Default: `false`
	UrlAppend pulumi.BoolPtrInput
	// Description of the frame redirection
	UrlRedirectDescription pulumi.StringPtrInput
	// FavIcon of the frame redirection
	UrlRedirectFavIcon pulumi.StringPtrInput
	// Keywords of the frame redirection
	UrlRedirectKeywords pulumi.StringPtrInput
	// Title of the frame redirection
	UrlRedirectTitle pulumi.StringPtrInput
	// Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
	UrlRedirectType pulumi.StringPtrInput
}

func (NameserverRecordArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nameserverRecordArgs)(nil)).Elem()
}

type NameserverRecordInput interface {
	pulumi.Input

	ToNameserverRecordOutput() NameserverRecordOutput
	ToNameserverRecordOutputWithContext(ctx context.Context) NameserverRecordOutput
}

func (*NameserverRecord) ElementType() reflect.Type {
	return reflect.TypeOf((**NameserverRecord)(nil)).Elem()
}

func (i *NameserverRecord) ToNameserverRecordOutput() NameserverRecordOutput {
	return i.ToNameserverRecordOutputWithContext(context.Background())
}

func (i *NameserverRecord) ToNameserverRecordOutputWithContext(ctx context.Context) NameserverRecordOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NameserverRecordOutput)
}

// NameserverRecordArrayInput is an input type that accepts NameserverRecordArray and NameserverRecordArrayOutput values.
// You can construct a concrete instance of `NameserverRecordArrayInput` via:
//
//	NameserverRecordArray{ NameserverRecordArgs{...} }
type NameserverRecordArrayInput interface {
	pulumi.Input

	ToNameserverRecordArrayOutput() NameserverRecordArrayOutput
	ToNameserverRecordArrayOutputWithContext(context.Context) NameserverRecordArrayOutput
}

type NameserverRecordArray []NameserverRecordInput

func (NameserverRecordArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NameserverRecord)(nil)).Elem()
}

func (i NameserverRecordArray) ToNameserverRecordArrayOutput() NameserverRecordArrayOutput {
	return i.ToNameserverRecordArrayOutputWithContext(context.Background())
}

func (i NameserverRecordArray) ToNameserverRecordArrayOutputWithContext(ctx context.Context) NameserverRecordArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NameserverRecordArrayOutput)
}

// NameserverRecordMapInput is an input type that accepts NameserverRecordMap and NameserverRecordMapOutput values.
// You can construct a concrete instance of `NameserverRecordMapInput` via:
//
//	NameserverRecordMap{ "key": NameserverRecordArgs{...} }
type NameserverRecordMapInput interface {
	pulumi.Input

	ToNameserverRecordMapOutput() NameserverRecordMapOutput
	ToNameserverRecordMapOutputWithContext(context.Context) NameserverRecordMapOutput
}

type NameserverRecordMap map[string]NameserverRecordInput

func (NameserverRecordMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NameserverRecord)(nil)).Elem()
}

func (i NameserverRecordMap) ToNameserverRecordMapOutput() NameserverRecordMapOutput {
	return i.ToNameserverRecordMapOutputWithContext(context.Background())
}

func (i NameserverRecordMap) ToNameserverRecordMapOutputWithContext(ctx context.Context) NameserverRecordMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NameserverRecordMapOutput)
}

type NameserverRecordOutput struct{ *pulumi.OutputState }

func (NameserverRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NameserverRecord)(nil)).Elem()
}

func (o NameserverRecordOutput) ToNameserverRecordOutput() NameserverRecordOutput {
	return o
}

func (o NameserverRecordOutput) ToNameserverRecordOutputWithContext(ctx context.Context) NameserverRecordOutput {
	return o
}

// Content of the nameserver record
func (o NameserverRecordOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.StringOutput { return v.Content }).(pulumi.StringOutput)
}

// Name of the domain
func (o NameserverRecordOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Name of the nameserver record
func (o NameserverRecordOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Priority of the nameserver record. Default: `0`
func (o NameserverRecordOutput) Prio() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.IntPtrOutput { return v.Prio }).(pulumi.IntPtrOutput)
}

// DNS domain id
func (o NameserverRecordOutput) RoId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.IntPtrOutput { return v.RoId }).(pulumi.IntPtrOutput)
}

// Execute command in testing mode. Default: `false`
func (o NameserverRecordOutput) Testing() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.BoolPtrOutput { return v.Testing }).(pulumi.BoolPtrOutput)
}

// TTL (time to live) of the nameserver record. Default: `3600`
func (o NameserverRecordOutput) Ttl() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.IntPtrOutput { return v.Ttl }).(pulumi.IntPtrOutput)
}

// Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`,
// `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
// `URI`, `URL`
func (o NameserverRecordOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// Append the path for redirection. Default: `false`
func (o NameserverRecordOutput) UrlAppend() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.BoolPtrOutput { return v.UrlAppend }).(pulumi.BoolPtrOutput)
}

// Description of the frame redirection
func (o NameserverRecordOutput) UrlRedirectDescription() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.StringPtrOutput { return v.UrlRedirectDescription }).(pulumi.StringPtrOutput)
}

// FavIcon of the frame redirection
func (o NameserverRecordOutput) UrlRedirectFavIcon() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.StringPtrOutput { return v.UrlRedirectFavIcon }).(pulumi.StringPtrOutput)
}

// Keywords of the frame redirection
func (o NameserverRecordOutput) UrlRedirectKeywords() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.StringPtrOutput { return v.UrlRedirectKeywords }).(pulumi.StringPtrOutput)
}

// Title of the frame redirection
func (o NameserverRecordOutput) UrlRedirectTitle() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.StringPtrOutput { return v.UrlRedirectTitle }).(pulumi.StringPtrOutput)
}

// Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
func (o NameserverRecordOutput) UrlRedirectType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NameserverRecord) pulumi.StringPtrOutput { return v.UrlRedirectType }).(pulumi.StringPtrOutput)
}

type NameserverRecordArrayOutput struct{ *pulumi.OutputState }

func (NameserverRecordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NameserverRecord)(nil)).Elem()
}

func (o NameserverRecordArrayOutput) ToNameserverRecordArrayOutput() NameserverRecordArrayOutput {
	return o
}

func (o NameserverRecordArrayOutput) ToNameserverRecordArrayOutputWithContext(ctx context.Context) NameserverRecordArrayOutput {
	return o
}

func (o NameserverRecordArrayOutput) Index(i pulumi.IntInput) NameserverRecordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NameserverRecord {
		return vs[0].([]*NameserverRecord)[vs[1].(int)]
	}).(NameserverRecordOutput)
}

type NameserverRecordMapOutput struct{ *pulumi.OutputState }

func (NameserverRecordMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NameserverRecord)(nil)).Elem()
}

func (o NameserverRecordMapOutput) ToNameserverRecordMapOutput() NameserverRecordMapOutput {
	return o
}

func (o NameserverRecordMapOutput) ToNameserverRecordMapOutputWithContext(ctx context.Context) NameserverRecordMapOutput {
	return o
}

func (o NameserverRecordMapOutput) MapIndex(k pulumi.StringInput) NameserverRecordOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NameserverRecord {
		return vs[0].(map[string]*NameserverRecord)[vs[1].(string)]
	}).(NameserverRecordOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NameserverRecordInput)(nil)).Elem(), &NameserverRecord{})
	pulumi.RegisterInputType(reflect.TypeOf((*NameserverRecordArrayInput)(nil)).Elem(), NameserverRecordArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NameserverRecordMapInput)(nil)).Elem(), NameserverRecordMap{})
	pulumi.RegisterOutputType(NameserverRecordOutput{})
	pulumi.RegisterOutputType(NameserverRecordArrayOutput{})
	pulumi.RegisterOutputType(NameserverRecordMapOutput{})
}
