// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package inwx

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wombelix/pulumi-inwx/sdk/go/inwx/internal"
)

var _ = internal.GetEnvOrDefault

type DomainContacts struct {
	// Id of the admin contact
	Admin int `pulumi:"admin"`
	// Id of the billing contact
	Billing int `pulumi:"billing"`
	// Id of the registrant contact
	Registrant int `pulumi:"registrant"`
	// Id of the tech contact
	Tech int `pulumi:"tech"`
}

// DomainContactsInput is an input type that accepts DomainContactsArgs and DomainContactsOutput values.
// You can construct a concrete instance of `DomainContactsInput` via:
//
//	DomainContactsArgs{...}
type DomainContactsInput interface {
	pulumi.Input

	ToDomainContactsOutput() DomainContactsOutput
	ToDomainContactsOutputWithContext(context.Context) DomainContactsOutput
}

type DomainContactsArgs struct {
	// Id of the admin contact
	Admin pulumi.IntInput `pulumi:"admin"`
	// Id of the billing contact
	Billing pulumi.IntInput `pulumi:"billing"`
	// Id of the registrant contact
	Registrant pulumi.IntInput `pulumi:"registrant"`
	// Id of the tech contact
	Tech pulumi.IntInput `pulumi:"tech"`
}

func (DomainContactsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainContacts)(nil)).Elem()
}

func (i DomainContactsArgs) ToDomainContactsOutput() DomainContactsOutput {
	return i.ToDomainContactsOutputWithContext(context.Background())
}

func (i DomainContactsArgs) ToDomainContactsOutputWithContext(ctx context.Context) DomainContactsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainContactsOutput)
}

func (i DomainContactsArgs) ToDomainContactsPtrOutput() DomainContactsPtrOutput {
	return i.ToDomainContactsPtrOutputWithContext(context.Background())
}

func (i DomainContactsArgs) ToDomainContactsPtrOutputWithContext(ctx context.Context) DomainContactsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainContactsOutput).ToDomainContactsPtrOutputWithContext(ctx)
}

// DomainContactsPtrInput is an input type that accepts DomainContactsArgs, DomainContactsPtr and DomainContactsPtrOutput values.
// You can construct a concrete instance of `DomainContactsPtrInput` via:
//
//	        DomainContactsArgs{...}
//
//	or:
//
//	        nil
type DomainContactsPtrInput interface {
	pulumi.Input

	ToDomainContactsPtrOutput() DomainContactsPtrOutput
	ToDomainContactsPtrOutputWithContext(context.Context) DomainContactsPtrOutput
}

type domainContactsPtrType DomainContactsArgs

func DomainContactsPtr(v *DomainContactsArgs) DomainContactsPtrInput {
	return (*domainContactsPtrType)(v)
}

func (*domainContactsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainContacts)(nil)).Elem()
}

func (i *domainContactsPtrType) ToDomainContactsPtrOutput() DomainContactsPtrOutput {
	return i.ToDomainContactsPtrOutputWithContext(context.Background())
}

func (i *domainContactsPtrType) ToDomainContactsPtrOutputWithContext(ctx context.Context) DomainContactsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainContactsPtrOutput)
}

type DomainContactsOutput struct{ *pulumi.OutputState }

func (DomainContactsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainContacts)(nil)).Elem()
}

func (o DomainContactsOutput) ToDomainContactsOutput() DomainContactsOutput {
	return o
}

func (o DomainContactsOutput) ToDomainContactsOutputWithContext(ctx context.Context) DomainContactsOutput {
	return o
}

func (o DomainContactsOutput) ToDomainContactsPtrOutput() DomainContactsPtrOutput {
	return o.ToDomainContactsPtrOutputWithContext(context.Background())
}

func (o DomainContactsOutput) ToDomainContactsPtrOutputWithContext(ctx context.Context) DomainContactsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DomainContacts) *DomainContacts {
		return &v
	}).(DomainContactsPtrOutput)
}

// Id of the admin contact
func (o DomainContactsOutput) Admin() pulumi.IntOutput {
	return o.ApplyT(func(v DomainContacts) int { return v.Admin }).(pulumi.IntOutput)
}

// Id of the billing contact
func (o DomainContactsOutput) Billing() pulumi.IntOutput {
	return o.ApplyT(func(v DomainContacts) int { return v.Billing }).(pulumi.IntOutput)
}

// Id of the registrant contact
func (o DomainContactsOutput) Registrant() pulumi.IntOutput {
	return o.ApplyT(func(v DomainContacts) int { return v.Registrant }).(pulumi.IntOutput)
}

// Id of the tech contact
func (o DomainContactsOutput) Tech() pulumi.IntOutput {
	return o.ApplyT(func(v DomainContacts) int { return v.Tech }).(pulumi.IntOutput)
}

type DomainContactsPtrOutput struct{ *pulumi.OutputState }

func (DomainContactsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainContacts)(nil)).Elem()
}

func (o DomainContactsPtrOutput) ToDomainContactsPtrOutput() DomainContactsPtrOutput {
	return o
}

func (o DomainContactsPtrOutput) ToDomainContactsPtrOutputWithContext(ctx context.Context) DomainContactsPtrOutput {
	return o
}

func (o DomainContactsPtrOutput) Elem() DomainContactsOutput {
	return o.ApplyT(func(v *DomainContacts) DomainContacts {
		if v != nil {
			return *v
		}
		var ret DomainContacts
		return ret
	}).(DomainContactsOutput)
}

// Id of the admin contact
func (o DomainContactsPtrOutput) Admin() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DomainContacts) *int {
		if v == nil {
			return nil
		}
		return &v.Admin
	}).(pulumi.IntPtrOutput)
}

// Id of the billing contact
func (o DomainContactsPtrOutput) Billing() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DomainContacts) *int {
		if v == nil {
			return nil
		}
		return &v.Billing
	}).(pulumi.IntPtrOutput)
}

// Id of the registrant contact
func (o DomainContactsPtrOutput) Registrant() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DomainContacts) *int {
		if v == nil {
			return nil
		}
		return &v.Registrant
	}).(pulumi.IntPtrOutput)
}

// Id of the tech contact
func (o DomainContactsPtrOutput) Tech() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DomainContacts) *int {
		if v == nil {
			return nil
		}
		return &v.Tech
	}).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainContactsInput)(nil)).Elem(), DomainContactsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainContactsPtrInput)(nil)).Elem(), DomainContactsArgs{})
	pulumi.RegisterOutputType(DomainContactsOutput{})
	pulumi.RegisterOutputType(DomainContactsPtrOutput{})
}
