# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .dnssec_key import *
from .domain import *
from .domain_contact import *
from .nameserver_record import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_inwx.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_inwx.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "inwx",
  "mod": "index/dnssecKey",
  "fqn": "pulumi_inwx",
  "classes": {
   "inwx:index/dnssecKey:DnssecKey": "DnssecKey"
  }
 },
 {
  "pkg": "inwx",
  "mod": "index/domain",
  "fqn": "pulumi_inwx",
  "classes": {
   "inwx:index/domain:Domain": "Domain"
  }
 },
 {
  "pkg": "inwx",
  "mod": "index/domainContact",
  "fqn": "pulumi_inwx",
  "classes": {
   "inwx:index/domainContact:DomainContact": "DomainContact"
  }
 },
 {
  "pkg": "inwx",
  "mod": "index/nameserverRecord",
  "fqn": "pulumi_inwx",
  "classes": {
   "inwx:index/nameserverRecord:NameserverRecord": "NameserverRecord"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "inwx",
  "token": "pulumi:providers:inwx",
  "fqn": "pulumi_inwx",
  "class": "Provider"
 }
]
"""
)
