# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'DomainContactsArgs',
]

@pulumi.input_type
class DomainContactsArgs:
    def __init__(__self__, *,
                 admin: pulumi.Input[int],
                 billing: pulumi.Input[int],
                 registrant: pulumi.Input[int],
                 tech: pulumi.Input[int]):
        """
        :param pulumi.Input[int] admin: Id of the admin contact
        :param pulumi.Input[int] billing: Id of the billing contact
        :param pulumi.Input[int] registrant: Id of the registrant contact
        :param pulumi.Input[int] tech: Id of the tech contact
        """
        pulumi.set(__self__, "admin", admin)
        pulumi.set(__self__, "billing", billing)
        pulumi.set(__self__, "registrant", registrant)
        pulumi.set(__self__, "tech", tech)

    @property
    @pulumi.getter
    def admin(self) -> pulumi.Input[int]:
        """
        Id of the admin contact
        """
        return pulumi.get(self, "admin")

    @admin.setter
    def admin(self, value: pulumi.Input[int]):
        pulumi.set(self, "admin", value)

    @property
    @pulumi.getter
    def billing(self) -> pulumi.Input[int]:
        """
        Id of the billing contact
        """
        return pulumi.get(self, "billing")

    @billing.setter
    def billing(self, value: pulumi.Input[int]):
        pulumi.set(self, "billing", value)

    @property
    @pulumi.getter
    def registrant(self) -> pulumi.Input[int]:
        """
        Id of the registrant contact
        """
        return pulumi.get(self, "registrant")

    @registrant.setter
    def registrant(self, value: pulumi.Input[int]):
        pulumi.set(self, "registrant", value)

    @property
    @pulumi.getter
    def tech(self) -> pulumi.Input[int]:
        """
        Id of the tech contact
        """
        return pulumi.get(self, "tech")

    @tech.setter
    def tech(self, value: pulumi.Input[int]):
        pulumi.set(self, "tech", value)


