# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['DnssecKeyArgs', 'DnssecKey']

@pulumi.input_type
class DnssecKeyArgs:
    def __init__(__self__, *,
                 algorithm: pulumi.Input[int],
                 domain: pulumi.Input[str],
                 public_key: pulumi.Input[str]):
        """
        The set of arguments for constructing a DnssecKey resource.
        :param pulumi.Input[int] algorithm: Algorithm used for the public key
        :param pulumi.Input[str] domain: Name of the domain
        :param pulumi.Input[str] public_key: Public key of the domain
        """
        pulumi.set(__self__, "algorithm", algorithm)
        pulumi.set(__self__, "domain", domain)
        pulumi.set(__self__, "public_key", public_key)

    @property
    @pulumi.getter
    def algorithm(self) -> pulumi.Input[int]:
        """
        Algorithm used for the public key
        """
        return pulumi.get(self, "algorithm")

    @algorithm.setter
    def algorithm(self, value: pulumi.Input[int]):
        pulumi.set(self, "algorithm", value)

    @property
    @pulumi.getter
    def domain(self) -> pulumi.Input[str]:
        """
        Name of the domain
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: pulumi.Input[str]):
        pulumi.set(self, "domain", value)

    @property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> pulumi.Input[str]:
        """
        Public key of the domain
        """
        return pulumi.get(self, "public_key")

    @public_key.setter
    def public_key(self, value: pulumi.Input[str]):
        pulumi.set(self, "public_key", value)


@pulumi.input_type
class _DnssecKeyState:
    def __init__(__self__, *,
                 algorithm: Optional[pulumi.Input[int]] = None,
                 digest: Optional[pulumi.Input[str]] = None,
                 digest_type: Optional[pulumi.Input[int]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 flag: Optional[pulumi.Input[int]] = None,
                 key_tag: Optional[pulumi.Input[int]] = None,
                 public_key: Optional[pulumi.Input[str]] = None,
                 status: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering DnssecKey resources.
        :param pulumi.Input[int] algorithm: Algorithm used for the public key
        :param pulumi.Input[str] digest: Computed digest for the public key
        :param pulumi.Input[int] digest_type: Digest type
        :param pulumi.Input[str] domain: Name of the domain
        :param pulumi.Input[int] flag: Key flag (256=ZSK, 257=KSK)
        :param pulumi.Input[int] key_tag: Key tag
        :param pulumi.Input[str] public_key: Public key of the domain
        :param pulumi.Input[str] status: DNSSEC status
        """
        if algorithm is not None:
            pulumi.set(__self__, "algorithm", algorithm)
        if digest is not None:
            pulumi.set(__self__, "digest", digest)
        if digest_type is not None:
            pulumi.set(__self__, "digest_type", digest_type)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if flag is not None:
            pulumi.set(__self__, "flag", flag)
        if key_tag is not None:
            pulumi.set(__self__, "key_tag", key_tag)
        if public_key is not None:
            pulumi.set(__self__, "public_key", public_key)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @property
    @pulumi.getter
    def algorithm(self) -> Optional[pulumi.Input[int]]:
        """
        Algorithm used for the public key
        """
        return pulumi.get(self, "algorithm")

    @algorithm.setter
    def algorithm(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "algorithm", value)

    @property
    @pulumi.getter
    def digest(self) -> Optional[pulumi.Input[str]]:
        """
        Computed digest for the public key
        """
        return pulumi.get(self, "digest")

    @digest.setter
    def digest(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "digest", value)

    @property
    @pulumi.getter(name="digestType")
    def digest_type(self) -> Optional[pulumi.Input[int]]:
        """
        Digest type
        """
        return pulumi.get(self, "digest_type")

    @digest_type.setter
    def digest_type(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "digest_type", value)

    @property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the domain
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "domain", value)

    @property
    @pulumi.getter
    def flag(self) -> Optional[pulumi.Input[int]]:
        """
        Key flag (256=ZSK, 257=KSK)
        """
        return pulumi.get(self, "flag")

    @flag.setter
    def flag(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "flag", value)

    @property
    @pulumi.getter(name="keyTag")
    def key_tag(self) -> Optional[pulumi.Input[int]]:
        """
        Key tag
        """
        return pulumi.get(self, "key_tag")

    @key_tag.setter
    def key_tag(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "key_tag", value)

    @property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> Optional[pulumi.Input[str]]:
        """
        Public key of the domain
        """
        return pulumi.get(self, "public_key")

    @public_key.setter
    def public_key(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "public_key", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[str]]:
        """
        DNSSEC status
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "status", value)


class DnssecKey(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 algorithm: Optional[pulumi.Input[int]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 public_key: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        ## # Resource: DnssecKey

        Provides a INWX DNSSEC key resource

        ## Example Usage

        ```python
        import pulumi
        import pulumi_inwx as inwx

        example_com = inwx.DnssecKey("exampleCom",
            algorithm="SHA256",
            domain="example.com",
            public_key="ac12c2...")
        ```
        ## Caveats

        ### Nameservers

        Can not be used in conjunction with INWX nameservers.

        ## Import

        INWX DNSSEC keys can be imported using the domain name and digest e.g.,

        ```sh
         $ pulumi import inwx:index/dnssecKey:DnssecKey example_com example.com/4E1243BD22C66E76C2BA9EDDC1F91394E57F9F83
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[int] algorithm: Algorithm used for the public key
        :param pulumi.Input[str] domain: Name of the domain
        :param pulumi.Input[str] public_key: Public key of the domain
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DnssecKeyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## # Resource: DnssecKey

        Provides a INWX DNSSEC key resource

        ## Example Usage

        ```python
        import pulumi
        import pulumi_inwx as inwx

        example_com = inwx.DnssecKey("exampleCom",
            algorithm="SHA256",
            domain="example.com",
            public_key="ac12c2...")
        ```
        ## Caveats

        ### Nameservers

        Can not be used in conjunction with INWX nameservers.

        ## Import

        INWX DNSSEC keys can be imported using the domain name and digest e.g.,

        ```sh
         $ pulumi import inwx:index/dnssecKey:DnssecKey example_com example.com/4E1243BD22C66E76C2BA9EDDC1F91394E57F9F83
        ```

        :param str resource_name: The name of the resource.
        :param DnssecKeyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DnssecKeyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 algorithm: Optional[pulumi.Input[int]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 public_key: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DnssecKeyArgs.__new__(DnssecKeyArgs)

            if algorithm is None and not opts.urn:
                raise TypeError("Missing required property 'algorithm'")
            __props__.__dict__["algorithm"] = algorithm
            if domain is None and not opts.urn:
                raise TypeError("Missing required property 'domain'")
            __props__.__dict__["domain"] = domain
            if public_key is None and not opts.urn:
                raise TypeError("Missing required property 'public_key'")
            __props__.__dict__["public_key"] = public_key
            __props__.__dict__["digest"] = None
            __props__.__dict__["digest_type"] = None
            __props__.__dict__["flag"] = None
            __props__.__dict__["key_tag"] = None
            __props__.__dict__["status"] = None
        super(DnssecKey, __self__).__init__(
            'inwx:index/dnssecKey:DnssecKey',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            algorithm: Optional[pulumi.Input[int]] = None,
            digest: Optional[pulumi.Input[str]] = None,
            digest_type: Optional[pulumi.Input[int]] = None,
            domain: Optional[pulumi.Input[str]] = None,
            flag: Optional[pulumi.Input[int]] = None,
            key_tag: Optional[pulumi.Input[int]] = None,
            public_key: Optional[pulumi.Input[str]] = None,
            status: Optional[pulumi.Input[str]] = None) -> 'DnssecKey':
        """
        Get an existing DnssecKey resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[int] algorithm: Algorithm used for the public key
        :param pulumi.Input[str] digest: Computed digest for the public key
        :param pulumi.Input[int] digest_type: Digest type
        :param pulumi.Input[str] domain: Name of the domain
        :param pulumi.Input[int] flag: Key flag (256=ZSK, 257=KSK)
        :param pulumi.Input[int] key_tag: Key tag
        :param pulumi.Input[str] public_key: Public key of the domain
        :param pulumi.Input[str] status: DNSSEC status
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DnssecKeyState.__new__(_DnssecKeyState)

        __props__.__dict__["algorithm"] = algorithm
        __props__.__dict__["digest"] = digest
        __props__.__dict__["digest_type"] = digest_type
        __props__.__dict__["domain"] = domain
        __props__.__dict__["flag"] = flag
        __props__.__dict__["key_tag"] = key_tag
        __props__.__dict__["public_key"] = public_key
        __props__.__dict__["status"] = status
        return DnssecKey(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def algorithm(self) -> pulumi.Output[int]:
        """
        Algorithm used for the public key
        """
        return pulumi.get(self, "algorithm")

    @property
    @pulumi.getter
    def digest(self) -> pulumi.Output[str]:
        """
        Computed digest for the public key
        """
        return pulumi.get(self, "digest")

    @property
    @pulumi.getter(name="digestType")
    def digest_type(self) -> pulumi.Output[int]:
        """
        Digest type
        """
        return pulumi.get(self, "digest_type")

    @property
    @pulumi.getter
    def domain(self) -> pulumi.Output[str]:
        """
        Name of the domain
        """
        return pulumi.get(self, "domain")

    @property
    @pulumi.getter
    def flag(self) -> pulumi.Output[int]:
        """
        Key flag (256=ZSK, 257=KSK)
        """
        return pulumi.get(self, "flag")

    @property
    @pulumi.getter(name="keyTag")
    def key_tag(self) -> pulumi.Output[int]:
        """
        Key tag
        """
        return pulumi.get(self, "key_tag")

    @property
    @pulumi.getter(name="publicKey")
    def public_key(self) -> pulumi.Output[str]:
        """
        Public key of the domain
        """
        return pulumi.get(self, "public_key")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[str]:
        """
        DNSSEC status
        """
        return pulumi.get(self, "status")

