# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['DomainArgs', 'Domain']

@pulumi.input_type
class DomainArgs:
    def __init__(__self__, *,
                 contacts: pulumi.Input['DomainContactsArgs'],
                 period: pulumi.Input[str],
                 extra_data: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 nameservers: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 renewal_mode: Optional[pulumi.Input[str]] = None,
                 transfer_lock: Optional[pulumi.Input[bool]] = None):
        """
        The set of arguments for constructing a Domain resource.
        :param pulumi.Input['DomainContactsArgs'] contacts: Contacts of the domain
        :param pulumi.Input[str] period: Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] extra_data: Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        :param pulumi.Input[str] name: Name of the domain
        :param pulumi.Input[Sequence[pulumi.Input[str]]] nameservers: Set of nameservers of the domain. Min Items: 1
        :param pulumi.Input[str] renewal_mode: Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        :param pulumi.Input[bool] transfer_lock: Whether the domain transfer lock should be enabled. Default: `true`
        """
        pulumi.set(__self__, "contacts", contacts)
        pulumi.set(__self__, "period", period)
        if extra_data is not None:
            pulumi.set(__self__, "extra_data", extra_data)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if nameservers is not None:
            pulumi.set(__self__, "nameservers", nameservers)
        if renewal_mode is not None:
            pulumi.set(__self__, "renewal_mode", renewal_mode)
        if transfer_lock is not None:
            pulumi.set(__self__, "transfer_lock", transfer_lock)

    @property
    @pulumi.getter
    def contacts(self) -> pulumi.Input['DomainContactsArgs']:
        """
        Contacts of the domain
        """
        return pulumi.get(self, "contacts")

    @contacts.setter
    def contacts(self, value: pulumi.Input['DomainContactsArgs']):
        pulumi.set(self, "contacts", value)

    @property
    @pulumi.getter
    def period(self) -> pulumi.Input[str]:
        """
        Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        """
        return pulumi.get(self, "period")

    @period.setter
    def period(self, value: pulumi.Input[str]):
        pulumi.set(self, "period", value)

    @property
    @pulumi.getter(name="extraData")
    def extra_data(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        """
        return pulumi.get(self, "extra_data")

    @extra_data.setter
    def extra_data(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "extra_data", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the domain
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def nameservers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Set of nameservers of the domain. Min Items: 1
        """
        return pulumi.get(self, "nameservers")

    @nameservers.setter
    def nameservers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "nameservers", value)

    @property
    @pulumi.getter(name="renewalMode")
    def renewal_mode(self) -> Optional[pulumi.Input[str]]:
        """
        Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        """
        return pulumi.get(self, "renewal_mode")

    @renewal_mode.setter
    def renewal_mode(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "renewal_mode", value)

    @property
    @pulumi.getter(name="transferLock")
    def transfer_lock(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the domain transfer lock should be enabled. Default: `true`
        """
        return pulumi.get(self, "transfer_lock")

    @transfer_lock.setter
    def transfer_lock(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "transfer_lock", value)


@pulumi.input_type
class _DomainState:
    def __init__(__self__, *,
                 contacts: Optional[pulumi.Input['DomainContactsArgs']] = None,
                 extra_data: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 nameservers: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 period: Optional[pulumi.Input[str]] = None,
                 renewal_mode: Optional[pulumi.Input[str]] = None,
                 transfer_lock: Optional[pulumi.Input[bool]] = None):
        """
        Input properties used for looking up and filtering Domain resources.
        :param pulumi.Input['DomainContactsArgs'] contacts: Contacts of the domain
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] extra_data: Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        :param pulumi.Input[str] name: Name of the domain
        :param pulumi.Input[Sequence[pulumi.Input[str]]] nameservers: Set of nameservers of the domain. Min Items: 1
        :param pulumi.Input[str] period: Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        :param pulumi.Input[str] renewal_mode: Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        :param pulumi.Input[bool] transfer_lock: Whether the domain transfer lock should be enabled. Default: `true`
        """
        if contacts is not None:
            pulumi.set(__self__, "contacts", contacts)
        if extra_data is not None:
            pulumi.set(__self__, "extra_data", extra_data)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if nameservers is not None:
            pulumi.set(__self__, "nameservers", nameservers)
        if period is not None:
            pulumi.set(__self__, "period", period)
        if renewal_mode is not None:
            pulumi.set(__self__, "renewal_mode", renewal_mode)
        if transfer_lock is not None:
            pulumi.set(__self__, "transfer_lock", transfer_lock)

    @property
    @pulumi.getter
    def contacts(self) -> Optional[pulumi.Input['DomainContactsArgs']]:
        """
        Contacts of the domain
        """
        return pulumi.get(self, "contacts")

    @contacts.setter
    def contacts(self, value: Optional[pulumi.Input['DomainContactsArgs']]):
        pulumi.set(self, "contacts", value)

    @property
    @pulumi.getter(name="extraData")
    def extra_data(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        """
        return pulumi.get(self, "extra_data")

    @extra_data.setter
    def extra_data(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "extra_data", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the domain
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def nameservers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Set of nameservers of the domain. Min Items: 1
        """
        return pulumi.get(self, "nameservers")

    @nameservers.setter
    def nameservers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "nameservers", value)

    @property
    @pulumi.getter
    def period(self) -> Optional[pulumi.Input[str]]:
        """
        Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        """
        return pulumi.get(self, "period")

    @period.setter
    def period(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "period", value)

    @property
    @pulumi.getter(name="renewalMode")
    def renewal_mode(self) -> Optional[pulumi.Input[str]]:
        """
        Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        """
        return pulumi.get(self, "renewal_mode")

    @renewal_mode.setter
    def renewal_mode(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "renewal_mode", value)

    @property
    @pulumi.getter(name="transferLock")
    def transfer_lock(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether the domain transfer lock should be enabled. Default: `true`
        """
        return pulumi.get(self, "transfer_lock")

    @transfer_lock.setter
    def transfer_lock(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "transfer_lock", value)


class Domain(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 contacts: Optional[pulumi.Input[pulumi.InputType['DomainContactsArgs']]] = None,
                 extra_data: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 nameservers: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 period: Optional[pulumi.Input[str]] = None,
                 renewal_mode: Optional[pulumi.Input[str]] = None,
                 transfer_lock: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        """
        ## Import

        INWX Domains can be imported using the domain name, e.g.,

        ```sh
         $ pulumi import inwx:index/domain:Domain example_com "example.com"
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[pulumi.InputType['DomainContactsArgs']] contacts: Contacts of the domain
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] extra_data: Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        :param pulumi.Input[str] name: Name of the domain
        :param pulumi.Input[Sequence[pulumi.Input[str]]] nameservers: Set of nameservers of the domain. Min Items: 1
        :param pulumi.Input[str] period: Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        :param pulumi.Input[str] renewal_mode: Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        :param pulumi.Input[bool] transfer_lock: Whether the domain transfer lock should be enabled. Default: `true`
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DomainArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Import

        INWX Domains can be imported using the domain name, e.g.,

        ```sh
         $ pulumi import inwx:index/domain:Domain example_com "example.com"
        ```

        :param str resource_name: The name of the resource.
        :param DomainArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DomainArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 contacts: Optional[pulumi.Input[pulumi.InputType['DomainContactsArgs']]] = None,
                 extra_data: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 nameservers: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 period: Optional[pulumi.Input[str]] = None,
                 renewal_mode: Optional[pulumi.Input[str]] = None,
                 transfer_lock: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DomainArgs.__new__(DomainArgs)

            if contacts is None and not opts.urn:
                raise TypeError("Missing required property 'contacts'")
            __props__.__dict__["contacts"] = contacts
            __props__.__dict__["extra_data"] = extra_data
            __props__.__dict__["name"] = name
            __props__.__dict__["nameservers"] = nameservers
            if period is None and not opts.urn:
                raise TypeError("Missing required property 'period'")
            __props__.__dict__["period"] = period
            __props__.__dict__["renewal_mode"] = renewal_mode
            __props__.__dict__["transfer_lock"] = transfer_lock
        super(Domain, __self__).__init__(
            'inwx:index/domain:Domain',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            contacts: Optional[pulumi.Input[pulumi.InputType['DomainContactsArgs']]] = None,
            extra_data: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
            name: Optional[pulumi.Input[str]] = None,
            nameservers: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
            period: Optional[pulumi.Input[str]] = None,
            renewal_mode: Optional[pulumi.Input[str]] = None,
            transfer_lock: Optional[pulumi.Input[bool]] = None) -> 'Domain':
        """
        Get an existing Domain resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[pulumi.InputType['DomainContactsArgs']] contacts: Contacts of the domain
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] extra_data: Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        :param pulumi.Input[str] name: Name of the domain
        :param pulumi.Input[Sequence[pulumi.Input[str]]] nameservers: Set of nameservers of the domain. Min Items: 1
        :param pulumi.Input[str] period: Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        :param pulumi.Input[str] renewal_mode: Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        :param pulumi.Input[bool] transfer_lock: Whether the domain transfer lock should be enabled. Default: `true`
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DomainState.__new__(_DomainState)

        __props__.__dict__["contacts"] = contacts
        __props__.__dict__["extra_data"] = extra_data
        __props__.__dict__["name"] = name
        __props__.__dict__["nameservers"] = nameservers
        __props__.__dict__["period"] = period
        __props__.__dict__["renewal_mode"] = renewal_mode
        __props__.__dict__["transfer_lock"] = transfer_lock
        return Domain(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def contacts(self) -> pulumi.Output['outputs.DomainContacts']:
        """
        Contacts of the domain
        """
        return pulumi.get(self, "contacts")

    @property
    @pulumi.getter(name="extraData")
    def extra_data(self) -> pulumi.Output[Optional[Mapping[str, str]]]:
        """
        Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
        """
        return pulumi.get(self, "extra_data")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        Name of the domain
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def nameservers(self) -> pulumi.Output[Optional[Sequence[str]]]:
        """
        Set of nameservers of the domain. Min Items: 1
        """
        return pulumi.get(self, "nameservers")

    @property
    @pulumi.getter
    def period(self) -> pulumi.Output[str]:
        """
        Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
        """
        return pulumi.get(self, "period")

    @property
    @pulumi.getter(name="renewalMode")
    def renewal_mode(self) -> pulumi.Output[Optional[str]]:
        """
        Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
        """
        return pulumi.get(self, "renewal_mode")

    @property
    @pulumi.getter(name="transferLock")
    def transfer_lock(self) -> pulumi.Output[Optional[bool]]:
        """
        Whether the domain transfer lock should be enabled. Default: `true`
        """
        return pulumi.get(self, "transfer_lock")

