# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['DomainContactArgs', 'DomainContact']

@pulumi.input_type
class DomainContactArgs:
    def __init__(__self__, *,
                 city: pulumi.Input[str],
                 country_code: pulumi.Input[str],
                 email: pulumi.Input[str],
                 phone_number: pulumi.Input[str],
                 postal_code: pulumi.Input[str],
                 street_address: pulumi.Input[str],
                 type: pulumi.Input[str],
                 fax: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization: Optional[pulumi.Input[str]] = None,
                 remarks: Optional[pulumi.Input[str]] = None,
                 state_province: Optional[pulumi.Input[str]] = None,
                 whois_protection: Optional[pulumi.Input[bool]] = None):
        """
        The set of arguments for constructing a DomainContact resource.
        :param pulumi.Input[str] city: City of the contact
        :param pulumi.Input[str] country_code: Country code of the contact. Must be two characters
        :param pulumi.Input[str] email: Contact email address
        :param pulumi.Input[str] phone_number: Phone number of the contact
        :param pulumi.Input[str] postal_code: Postal Code/Zipcode of the contact
        :param pulumi.Input[str] street_address: Street Address of the contact
        :param pulumi.Input[str] type: Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        :param pulumi.Input[str] fax: Fax number of the contact
        :param pulumi.Input[str] name: First and lastname of the contact
        :param pulumi.Input[str] organization: The legal name of the organization. Required for types other than person
        :param pulumi.Input[str] remarks: Custom description of the contact
        :param pulumi.Input[str] state_province: State/Province name of the contact
        :param pulumi.Input[bool] whois_protection: Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        """
        pulumi.set(__self__, "city", city)
        pulumi.set(__self__, "country_code", country_code)
        pulumi.set(__self__, "email", email)
        pulumi.set(__self__, "phone_number", phone_number)
        pulumi.set(__self__, "postal_code", postal_code)
        pulumi.set(__self__, "street_address", street_address)
        pulumi.set(__self__, "type", type)
        if fax is not None:
            pulumi.set(__self__, "fax", fax)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if remarks is not None:
            pulumi.set(__self__, "remarks", remarks)
        if state_province is not None:
            pulumi.set(__self__, "state_province", state_province)
        if whois_protection is not None:
            pulumi.set(__self__, "whois_protection", whois_protection)

    @property
    @pulumi.getter
    def city(self) -> pulumi.Input[str]:
        """
        City of the contact
        """
        return pulumi.get(self, "city")

    @city.setter
    def city(self, value: pulumi.Input[str]):
        pulumi.set(self, "city", value)

    @property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> pulumi.Input[str]:
        """
        Country code of the contact. Must be two characters
        """
        return pulumi.get(self, "country_code")

    @country_code.setter
    def country_code(self, value: pulumi.Input[str]):
        pulumi.set(self, "country_code", value)

    @property
    @pulumi.getter
    def email(self) -> pulumi.Input[str]:
        """
        Contact email address
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[str]):
        pulumi.set(self, "email", value)

    @property
    @pulumi.getter(name="phoneNumber")
    def phone_number(self) -> pulumi.Input[str]:
        """
        Phone number of the contact
        """
        return pulumi.get(self, "phone_number")

    @phone_number.setter
    def phone_number(self, value: pulumi.Input[str]):
        pulumi.set(self, "phone_number", value)

    @property
    @pulumi.getter(name="postalCode")
    def postal_code(self) -> pulumi.Input[str]:
        """
        Postal Code/Zipcode of the contact
        """
        return pulumi.get(self, "postal_code")

    @postal_code.setter
    def postal_code(self, value: pulumi.Input[str]):
        pulumi.set(self, "postal_code", value)

    @property
    @pulumi.getter(name="streetAddress")
    def street_address(self) -> pulumi.Input[str]:
        """
        Street Address of the contact
        """
        return pulumi.get(self, "street_address")

    @street_address.setter
    def street_address(self, value: pulumi.Input[str]):
        pulumi.set(self, "street_address", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        """
        Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def fax(self) -> Optional[pulumi.Input[str]]:
        """
        Fax number of the contact
        """
        return pulumi.get(self, "fax")

    @fax.setter
    def fax(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "fax", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        First and lastname of the contact
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[str]]:
        """
        The legal name of the organization. Required for types other than person
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "organization", value)

    @property
    @pulumi.getter
    def remarks(self) -> Optional[pulumi.Input[str]]:
        """
        Custom description of the contact
        """
        return pulumi.get(self, "remarks")

    @remarks.setter
    def remarks(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "remarks", value)

    @property
    @pulumi.getter(name="stateProvince")
    def state_province(self) -> Optional[pulumi.Input[str]]:
        """
        State/Province name of the contact
        """
        return pulumi.get(self, "state_province")

    @state_province.setter
    def state_province(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "state_province", value)

    @property
    @pulumi.getter(name="whoisProtection")
    def whois_protection(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        """
        return pulumi.get(self, "whois_protection")

    @whois_protection.setter
    def whois_protection(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "whois_protection", value)


@pulumi.input_type
class _DomainContactState:
    def __init__(__self__, *,
                 city: Optional[pulumi.Input[str]] = None,
                 country_code: Optional[pulumi.Input[str]] = None,
                 email: Optional[pulumi.Input[str]] = None,
                 fax: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization: Optional[pulumi.Input[str]] = None,
                 phone_number: Optional[pulumi.Input[str]] = None,
                 postal_code: Optional[pulumi.Input[str]] = None,
                 remarks: Optional[pulumi.Input[str]] = None,
                 state_province: Optional[pulumi.Input[str]] = None,
                 street_address: Optional[pulumi.Input[str]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 whois_protection: Optional[pulumi.Input[bool]] = None):
        """
        Input properties used for looking up and filtering DomainContact resources.
        :param pulumi.Input[str] city: City of the contact
        :param pulumi.Input[str] country_code: Country code of the contact. Must be two characters
        :param pulumi.Input[str] email: Contact email address
        :param pulumi.Input[str] fax: Fax number of the contact
        :param pulumi.Input[str] name: First and lastname of the contact
        :param pulumi.Input[str] organization: The legal name of the organization. Required for types other than person
        :param pulumi.Input[str] phone_number: Phone number of the contact
        :param pulumi.Input[str] postal_code: Postal Code/Zipcode of the contact
        :param pulumi.Input[str] remarks: Custom description of the contact
        :param pulumi.Input[str] state_province: State/Province name of the contact
        :param pulumi.Input[str] street_address: Street Address of the contact
        :param pulumi.Input[str] type: Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        :param pulumi.Input[bool] whois_protection: Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        """
        if city is not None:
            pulumi.set(__self__, "city", city)
        if country_code is not None:
            pulumi.set(__self__, "country_code", country_code)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if fax is not None:
            pulumi.set(__self__, "fax", fax)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if phone_number is not None:
            pulumi.set(__self__, "phone_number", phone_number)
        if postal_code is not None:
            pulumi.set(__self__, "postal_code", postal_code)
        if remarks is not None:
            pulumi.set(__self__, "remarks", remarks)
        if state_province is not None:
            pulumi.set(__self__, "state_province", state_province)
        if street_address is not None:
            pulumi.set(__self__, "street_address", street_address)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if whois_protection is not None:
            pulumi.set(__self__, "whois_protection", whois_protection)

    @property
    @pulumi.getter
    def city(self) -> Optional[pulumi.Input[str]]:
        """
        City of the contact
        """
        return pulumi.get(self, "city")

    @city.setter
    def city(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "city", value)

    @property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> Optional[pulumi.Input[str]]:
        """
        Country code of the contact. Must be two characters
        """
        return pulumi.get(self, "country_code")

    @country_code.setter
    def country_code(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "country_code", value)

    @property
    @pulumi.getter
    def email(self) -> Optional[pulumi.Input[str]]:
        """
        Contact email address
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "email", value)

    @property
    @pulumi.getter
    def fax(self) -> Optional[pulumi.Input[str]]:
        """
        Fax number of the contact
        """
        return pulumi.get(self, "fax")

    @fax.setter
    def fax(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "fax", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        First and lastname of the contact
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[str]]:
        """
        The legal name of the organization. Required for types other than person
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "organization", value)

    @property
    @pulumi.getter(name="phoneNumber")
    def phone_number(self) -> Optional[pulumi.Input[str]]:
        """
        Phone number of the contact
        """
        return pulumi.get(self, "phone_number")

    @phone_number.setter
    def phone_number(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "phone_number", value)

    @property
    @pulumi.getter(name="postalCode")
    def postal_code(self) -> Optional[pulumi.Input[str]]:
        """
        Postal Code/Zipcode of the contact
        """
        return pulumi.get(self, "postal_code")

    @postal_code.setter
    def postal_code(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "postal_code", value)

    @property
    @pulumi.getter
    def remarks(self) -> Optional[pulumi.Input[str]]:
        """
        Custom description of the contact
        """
        return pulumi.get(self, "remarks")

    @remarks.setter
    def remarks(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "remarks", value)

    @property
    @pulumi.getter(name="stateProvince")
    def state_province(self) -> Optional[pulumi.Input[str]]:
        """
        State/Province name of the contact
        """
        return pulumi.get(self, "state_province")

    @state_province.setter
    def state_province(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "state_province", value)

    @property
    @pulumi.getter(name="streetAddress")
    def street_address(self) -> Optional[pulumi.Input[str]]:
        """
        Street Address of the contact
        """
        return pulumi.get(self, "street_address")

    @street_address.setter
    def street_address(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "street_address", value)

    @property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[str]]:
        """
        Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter(name="whoisProtection")
    def whois_protection(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        """
        return pulumi.get(self, "whois_protection")

    @whois_protection.setter
    def whois_protection(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "whois_protection", value)


class DomainContact(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 city: Optional[pulumi.Input[str]] = None,
                 country_code: Optional[pulumi.Input[str]] = None,
                 email: Optional[pulumi.Input[str]] = None,
                 fax: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization: Optional[pulumi.Input[str]] = None,
                 phone_number: Optional[pulumi.Input[str]] = None,
                 postal_code: Optional[pulumi.Input[str]] = None,
                 remarks: Optional[pulumi.Input[str]] = None,
                 state_province: Optional[pulumi.Input[str]] = None,
                 street_address: Optional[pulumi.Input[str]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 whois_protection: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        """
        ## # Resource: DomainContact

        Provides a INWX domain contact resource

        ## Example Usage

        ```python
        import pulumi
        import pulumi_inwx as inwx

        example_person = inwx.DomainContact("examplePerson",
            city="Example City",
            country_code="EX",
            email="person@example.invalid",
            phone_number="+00.00000000000",
            postal_code="0",
            state_province="Example State",
            street_address="Example Street 0",
            type="PERSON")
        ```

        ## Import

        INWX domain contacts can be imported using the `id`, e.g.,

        ```sh
         $ pulumi import inwx:index/domainContact:DomainContact inwx_domain_contact 2147483647
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] city: City of the contact
        :param pulumi.Input[str] country_code: Country code of the contact. Must be two characters
        :param pulumi.Input[str] email: Contact email address
        :param pulumi.Input[str] fax: Fax number of the contact
        :param pulumi.Input[str] name: First and lastname of the contact
        :param pulumi.Input[str] organization: The legal name of the organization. Required for types other than person
        :param pulumi.Input[str] phone_number: Phone number of the contact
        :param pulumi.Input[str] postal_code: Postal Code/Zipcode of the contact
        :param pulumi.Input[str] remarks: Custom description of the contact
        :param pulumi.Input[str] state_province: State/Province name of the contact
        :param pulumi.Input[str] street_address: Street Address of the contact
        :param pulumi.Input[str] type: Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        :param pulumi.Input[bool] whois_protection: Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DomainContactArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## # Resource: DomainContact

        Provides a INWX domain contact resource

        ## Example Usage

        ```python
        import pulumi
        import pulumi_inwx as inwx

        example_person = inwx.DomainContact("examplePerson",
            city="Example City",
            country_code="EX",
            email="person@example.invalid",
            phone_number="+00.00000000000",
            postal_code="0",
            state_province="Example State",
            street_address="Example Street 0",
            type="PERSON")
        ```

        ## Import

        INWX domain contacts can be imported using the `id`, e.g.,

        ```sh
         $ pulumi import inwx:index/domainContact:DomainContact inwx_domain_contact 2147483647
        ```

        :param str resource_name: The name of the resource.
        :param DomainContactArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DomainContactArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 city: Optional[pulumi.Input[str]] = None,
                 country_code: Optional[pulumi.Input[str]] = None,
                 email: Optional[pulumi.Input[str]] = None,
                 fax: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 organization: Optional[pulumi.Input[str]] = None,
                 phone_number: Optional[pulumi.Input[str]] = None,
                 postal_code: Optional[pulumi.Input[str]] = None,
                 remarks: Optional[pulumi.Input[str]] = None,
                 state_province: Optional[pulumi.Input[str]] = None,
                 street_address: Optional[pulumi.Input[str]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 whois_protection: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DomainContactArgs.__new__(DomainContactArgs)

            if city is None and not opts.urn:
                raise TypeError("Missing required property 'city'")
            __props__.__dict__["city"] = city
            if country_code is None and not opts.urn:
                raise TypeError("Missing required property 'country_code'")
            __props__.__dict__["country_code"] = country_code
            if email is None and not opts.urn:
                raise TypeError("Missing required property 'email'")
            __props__.__dict__["email"] = email
            __props__.__dict__["fax"] = fax
            __props__.__dict__["name"] = name
            __props__.__dict__["organization"] = organization
            if phone_number is None and not opts.urn:
                raise TypeError("Missing required property 'phone_number'")
            __props__.__dict__["phone_number"] = phone_number
            if postal_code is None and not opts.urn:
                raise TypeError("Missing required property 'postal_code'")
            __props__.__dict__["postal_code"] = postal_code
            __props__.__dict__["remarks"] = remarks
            __props__.__dict__["state_province"] = state_province
            if street_address is None and not opts.urn:
                raise TypeError("Missing required property 'street_address'")
            __props__.__dict__["street_address"] = street_address
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["whois_protection"] = whois_protection
        super(DomainContact, __self__).__init__(
            'inwx:index/domainContact:DomainContact',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            city: Optional[pulumi.Input[str]] = None,
            country_code: Optional[pulumi.Input[str]] = None,
            email: Optional[pulumi.Input[str]] = None,
            fax: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            organization: Optional[pulumi.Input[str]] = None,
            phone_number: Optional[pulumi.Input[str]] = None,
            postal_code: Optional[pulumi.Input[str]] = None,
            remarks: Optional[pulumi.Input[str]] = None,
            state_province: Optional[pulumi.Input[str]] = None,
            street_address: Optional[pulumi.Input[str]] = None,
            type: Optional[pulumi.Input[str]] = None,
            whois_protection: Optional[pulumi.Input[bool]] = None) -> 'DomainContact':
        """
        Get an existing DomainContact resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] city: City of the contact
        :param pulumi.Input[str] country_code: Country code of the contact. Must be two characters
        :param pulumi.Input[str] email: Contact email address
        :param pulumi.Input[str] fax: Fax number of the contact
        :param pulumi.Input[str] name: First and lastname of the contact
        :param pulumi.Input[str] organization: The legal name of the organization. Required for types other than person
        :param pulumi.Input[str] phone_number: Phone number of the contact
        :param pulumi.Input[str] postal_code: Postal Code/Zipcode of the contact
        :param pulumi.Input[str] remarks: Custom description of the contact
        :param pulumi.Input[str] state_province: State/Province name of the contact
        :param pulumi.Input[str] street_address: Street Address of the contact
        :param pulumi.Input[str] type: Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        :param pulumi.Input[bool] whois_protection: Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DomainContactState.__new__(_DomainContactState)

        __props__.__dict__["city"] = city
        __props__.__dict__["country_code"] = country_code
        __props__.__dict__["email"] = email
        __props__.__dict__["fax"] = fax
        __props__.__dict__["name"] = name
        __props__.__dict__["organization"] = organization
        __props__.__dict__["phone_number"] = phone_number
        __props__.__dict__["postal_code"] = postal_code
        __props__.__dict__["remarks"] = remarks
        __props__.__dict__["state_province"] = state_province
        __props__.__dict__["street_address"] = street_address
        __props__.__dict__["type"] = type
        __props__.__dict__["whois_protection"] = whois_protection
        return DomainContact(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def city(self) -> pulumi.Output[str]:
        """
        City of the contact
        """
        return pulumi.get(self, "city")

    @property
    @pulumi.getter(name="countryCode")
    def country_code(self) -> pulumi.Output[str]:
        """
        Country code of the contact. Must be two characters
        """
        return pulumi.get(self, "country_code")

    @property
    @pulumi.getter
    def email(self) -> pulumi.Output[str]:
        """
        Contact email address
        """
        return pulumi.get(self, "email")

    @property
    @pulumi.getter
    def fax(self) -> pulumi.Output[Optional[str]]:
        """
        Fax number of the contact
        """
        return pulumi.get(self, "fax")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        First and lastname of the contact
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def organization(self) -> pulumi.Output[Optional[str]]:
        """
        The legal name of the organization. Required for types other than person
        """
        return pulumi.get(self, "organization")

    @property
    @pulumi.getter(name="phoneNumber")
    def phone_number(self) -> pulumi.Output[str]:
        """
        Phone number of the contact
        """
        return pulumi.get(self, "phone_number")

    @property
    @pulumi.getter(name="postalCode")
    def postal_code(self) -> pulumi.Output[str]:
        """
        Postal Code/Zipcode of the contact
        """
        return pulumi.get(self, "postal_code")

    @property
    @pulumi.getter
    def remarks(self) -> pulumi.Output[Optional[str]]:
        """
        Custom description of the contact
        """
        return pulumi.get(self, "remarks")

    @property
    @pulumi.getter(name="stateProvince")
    def state_province(self) -> pulumi.Output[Optional[str]]:
        """
        State/Province name of the contact
        """
        return pulumi.get(self, "state_province")

    @property
    @pulumi.getter(name="streetAddress")
    def street_address(self) -> pulumi.Output[str]:
        """
        Street Address of the contact
        """
        return pulumi.get(self, "street_address")

    @property
    @pulumi.getter
    def type(self) -> pulumi.Output[str]:
        """
        Type of contact. One of: `ORG`, `PERSON`, `ROLE`
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter(name="whoisProtection")
    def whois_protection(self) -> pulumi.Output[Optional[bool]]:
        """
        Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
        """
        return pulumi.get(self, "whois_protection")

