# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['NameserverRecordArgs', 'NameserverRecord']

@pulumi.input_type
class NameserverRecordArgs:
    def __init__(__self__, *,
                 content: pulumi.Input[str],
                 domain: pulumi.Input[str],
                 type: pulumi.Input[str],
                 name: Optional[pulumi.Input[str]] = None,
                 prio: Optional[pulumi.Input[int]] = None,
                 ro_id: Optional[pulumi.Input[int]] = None,
                 testing: Optional[pulumi.Input[bool]] = None,
                 ttl: Optional[pulumi.Input[int]] = None,
                 url_append: Optional[pulumi.Input[bool]] = None,
                 url_redirect_description: Optional[pulumi.Input[str]] = None,
                 url_redirect_fav_icon: Optional[pulumi.Input[str]] = None,
                 url_redirect_keywords: Optional[pulumi.Input[str]] = None,
                 url_redirect_title: Optional[pulumi.Input[str]] = None,
                 url_redirect_type: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a NameserverRecord resource.
        :param pulumi.Input[str] content: Content of the nameserver record
        :param pulumi.Input[str] domain: Name of the domain
        :param pulumi.Input[str] type: Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
               `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
               `URI`, `URL`
        :param pulumi.Input[str] name: Name of the nameserver record
        :param pulumi.Input[int] prio: Priority of the nameserver record. Default: `0`
        :param pulumi.Input[int] ro_id: DNS domain id
        :param pulumi.Input[bool] testing: Execute command in testing mode. Default: `false`
        :param pulumi.Input[int] ttl: TTL (time to live) of the nameserver record. Default: `3600`
        :param pulumi.Input[bool] url_append: Append the path for redirection. Default: `false`
        :param pulumi.Input[str] url_redirect_description: Description of the frame redirection
        :param pulumi.Input[str] url_redirect_fav_icon: FavIcon of the frame redirection
        :param pulumi.Input[str] url_redirect_keywords: Keywords of the frame redirection
        :param pulumi.Input[str] url_redirect_title: Title of the frame redirection
        :param pulumi.Input[str] url_redirect_type: Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        """
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "domain", domain)
        pulumi.set(__self__, "type", type)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if prio is not None:
            pulumi.set(__self__, "prio", prio)
        if ro_id is not None:
            pulumi.set(__self__, "ro_id", ro_id)
        if testing is not None:
            pulumi.set(__self__, "testing", testing)
        if ttl is not None:
            pulumi.set(__self__, "ttl", ttl)
        if url_append is not None:
            pulumi.set(__self__, "url_append", url_append)
        if url_redirect_description is not None:
            pulumi.set(__self__, "url_redirect_description", url_redirect_description)
        if url_redirect_fav_icon is not None:
            pulumi.set(__self__, "url_redirect_fav_icon", url_redirect_fav_icon)
        if url_redirect_keywords is not None:
            pulumi.set(__self__, "url_redirect_keywords", url_redirect_keywords)
        if url_redirect_title is not None:
            pulumi.set(__self__, "url_redirect_title", url_redirect_title)
        if url_redirect_type is not None:
            pulumi.set(__self__, "url_redirect_type", url_redirect_type)

    @property
    @pulumi.getter
    def content(self) -> pulumi.Input[str]:
        """
        Content of the nameserver record
        """
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: pulumi.Input[str]):
        pulumi.set(self, "content", value)

    @property
    @pulumi.getter
    def domain(self) -> pulumi.Input[str]:
        """
        Name of the domain
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: pulumi.Input[str]):
        pulumi.set(self, "domain", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        """
        Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
        `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
        `URI`, `URL`
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the nameserver record
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def prio(self) -> Optional[pulumi.Input[int]]:
        """
        Priority of the nameserver record. Default: `0`
        """
        return pulumi.get(self, "prio")

    @prio.setter
    def prio(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "prio", value)

    @property
    @pulumi.getter(name="roId")
    def ro_id(self) -> Optional[pulumi.Input[int]]:
        """
        DNS domain id
        """
        return pulumi.get(self, "ro_id")

    @ro_id.setter
    def ro_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "ro_id", value)

    @property
    @pulumi.getter
    def testing(self) -> Optional[pulumi.Input[bool]]:
        """
        Execute command in testing mode. Default: `false`
        """
        return pulumi.get(self, "testing")

    @testing.setter
    def testing(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "testing", value)

    @property
    @pulumi.getter
    def ttl(self) -> Optional[pulumi.Input[int]]:
        """
        TTL (time to live) of the nameserver record. Default: `3600`
        """
        return pulumi.get(self, "ttl")

    @ttl.setter
    def ttl(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "ttl", value)

    @property
    @pulumi.getter(name="urlAppend")
    def url_append(self) -> Optional[pulumi.Input[bool]]:
        """
        Append the path for redirection. Default: `false`
        """
        return pulumi.get(self, "url_append")

    @url_append.setter
    def url_append(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "url_append", value)

    @property
    @pulumi.getter(name="urlRedirectDescription")
    def url_redirect_description(self) -> Optional[pulumi.Input[str]]:
        """
        Description of the frame redirection
        """
        return pulumi.get(self, "url_redirect_description")

    @url_redirect_description.setter
    def url_redirect_description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_description", value)

    @property
    @pulumi.getter(name="urlRedirectFavIcon")
    def url_redirect_fav_icon(self) -> Optional[pulumi.Input[str]]:
        """
        FavIcon of the frame redirection
        """
        return pulumi.get(self, "url_redirect_fav_icon")

    @url_redirect_fav_icon.setter
    def url_redirect_fav_icon(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_fav_icon", value)

    @property
    @pulumi.getter(name="urlRedirectKeywords")
    def url_redirect_keywords(self) -> Optional[pulumi.Input[str]]:
        """
        Keywords of the frame redirection
        """
        return pulumi.get(self, "url_redirect_keywords")

    @url_redirect_keywords.setter
    def url_redirect_keywords(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_keywords", value)

    @property
    @pulumi.getter(name="urlRedirectTitle")
    def url_redirect_title(self) -> Optional[pulumi.Input[str]]:
        """
        Title of the frame redirection
        """
        return pulumi.get(self, "url_redirect_title")

    @url_redirect_title.setter
    def url_redirect_title(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_title", value)

    @property
    @pulumi.getter(name="urlRedirectType")
    def url_redirect_type(self) -> Optional[pulumi.Input[str]]:
        """
        Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        """
        return pulumi.get(self, "url_redirect_type")

    @url_redirect_type.setter
    def url_redirect_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_type", value)


@pulumi.input_type
class _NameserverRecordState:
    def __init__(__self__, *,
                 content: Optional[pulumi.Input[str]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 prio: Optional[pulumi.Input[int]] = None,
                 ro_id: Optional[pulumi.Input[int]] = None,
                 testing: Optional[pulumi.Input[bool]] = None,
                 ttl: Optional[pulumi.Input[int]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 url_append: Optional[pulumi.Input[bool]] = None,
                 url_redirect_description: Optional[pulumi.Input[str]] = None,
                 url_redirect_fav_icon: Optional[pulumi.Input[str]] = None,
                 url_redirect_keywords: Optional[pulumi.Input[str]] = None,
                 url_redirect_title: Optional[pulumi.Input[str]] = None,
                 url_redirect_type: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering NameserverRecord resources.
        :param pulumi.Input[str] content: Content of the nameserver record
        :param pulumi.Input[str] domain: Name of the domain
        :param pulumi.Input[str] name: Name of the nameserver record
        :param pulumi.Input[int] prio: Priority of the nameserver record. Default: `0`
        :param pulumi.Input[int] ro_id: DNS domain id
        :param pulumi.Input[bool] testing: Execute command in testing mode. Default: `false`
        :param pulumi.Input[int] ttl: TTL (time to live) of the nameserver record. Default: `3600`
        :param pulumi.Input[str] type: Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
               `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
               `URI`, `URL`
        :param pulumi.Input[bool] url_append: Append the path for redirection. Default: `false`
        :param pulumi.Input[str] url_redirect_description: Description of the frame redirection
        :param pulumi.Input[str] url_redirect_fav_icon: FavIcon of the frame redirection
        :param pulumi.Input[str] url_redirect_keywords: Keywords of the frame redirection
        :param pulumi.Input[str] url_redirect_title: Title of the frame redirection
        :param pulumi.Input[str] url_redirect_type: Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        """
        if content is not None:
            pulumi.set(__self__, "content", content)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if prio is not None:
            pulumi.set(__self__, "prio", prio)
        if ro_id is not None:
            pulumi.set(__self__, "ro_id", ro_id)
        if testing is not None:
            pulumi.set(__self__, "testing", testing)
        if ttl is not None:
            pulumi.set(__self__, "ttl", ttl)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if url_append is not None:
            pulumi.set(__self__, "url_append", url_append)
        if url_redirect_description is not None:
            pulumi.set(__self__, "url_redirect_description", url_redirect_description)
        if url_redirect_fav_icon is not None:
            pulumi.set(__self__, "url_redirect_fav_icon", url_redirect_fav_icon)
        if url_redirect_keywords is not None:
            pulumi.set(__self__, "url_redirect_keywords", url_redirect_keywords)
        if url_redirect_title is not None:
            pulumi.set(__self__, "url_redirect_title", url_redirect_title)
        if url_redirect_type is not None:
            pulumi.set(__self__, "url_redirect_type", url_redirect_type)

    @property
    @pulumi.getter
    def content(self) -> Optional[pulumi.Input[str]]:
        """
        Content of the nameserver record
        """
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "content", value)

    @property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the domain
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "domain", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the nameserver record
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def prio(self) -> Optional[pulumi.Input[int]]:
        """
        Priority of the nameserver record. Default: `0`
        """
        return pulumi.get(self, "prio")

    @prio.setter
    def prio(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "prio", value)

    @property
    @pulumi.getter(name="roId")
    def ro_id(self) -> Optional[pulumi.Input[int]]:
        """
        DNS domain id
        """
        return pulumi.get(self, "ro_id")

    @ro_id.setter
    def ro_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "ro_id", value)

    @property
    @pulumi.getter
    def testing(self) -> Optional[pulumi.Input[bool]]:
        """
        Execute command in testing mode. Default: `false`
        """
        return pulumi.get(self, "testing")

    @testing.setter
    def testing(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "testing", value)

    @property
    @pulumi.getter
    def ttl(self) -> Optional[pulumi.Input[int]]:
        """
        TTL (time to live) of the nameserver record. Default: `3600`
        """
        return pulumi.get(self, "ttl")

    @ttl.setter
    def ttl(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "ttl", value)

    @property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[str]]:
        """
        Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
        `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
        `URI`, `URL`
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter(name="urlAppend")
    def url_append(self) -> Optional[pulumi.Input[bool]]:
        """
        Append the path for redirection. Default: `false`
        """
        return pulumi.get(self, "url_append")

    @url_append.setter
    def url_append(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "url_append", value)

    @property
    @pulumi.getter(name="urlRedirectDescription")
    def url_redirect_description(self) -> Optional[pulumi.Input[str]]:
        """
        Description of the frame redirection
        """
        return pulumi.get(self, "url_redirect_description")

    @url_redirect_description.setter
    def url_redirect_description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_description", value)

    @property
    @pulumi.getter(name="urlRedirectFavIcon")
    def url_redirect_fav_icon(self) -> Optional[pulumi.Input[str]]:
        """
        FavIcon of the frame redirection
        """
        return pulumi.get(self, "url_redirect_fav_icon")

    @url_redirect_fav_icon.setter
    def url_redirect_fav_icon(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_fav_icon", value)

    @property
    @pulumi.getter(name="urlRedirectKeywords")
    def url_redirect_keywords(self) -> Optional[pulumi.Input[str]]:
        """
        Keywords of the frame redirection
        """
        return pulumi.get(self, "url_redirect_keywords")

    @url_redirect_keywords.setter
    def url_redirect_keywords(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_keywords", value)

    @property
    @pulumi.getter(name="urlRedirectTitle")
    def url_redirect_title(self) -> Optional[pulumi.Input[str]]:
        """
        Title of the frame redirection
        """
        return pulumi.get(self, "url_redirect_title")

    @url_redirect_title.setter
    def url_redirect_title(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_title", value)

    @property
    @pulumi.getter(name="urlRedirectType")
    def url_redirect_type(self) -> Optional[pulumi.Input[str]]:
        """
        Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        """
        return pulumi.get(self, "url_redirect_type")

    @url_redirect_type.setter
    def url_redirect_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url_redirect_type", value)


class NameserverRecord(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 content: Optional[pulumi.Input[str]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 prio: Optional[pulumi.Input[int]] = None,
                 ro_id: Optional[pulumi.Input[int]] = None,
                 testing: Optional[pulumi.Input[bool]] = None,
                 ttl: Optional[pulumi.Input[int]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 url_append: Optional[pulumi.Input[bool]] = None,
                 url_redirect_description: Optional[pulumi.Input[str]] = None,
                 url_redirect_fav_icon: Optional[pulumi.Input[str]] = None,
                 url_redirect_keywords: Optional[pulumi.Input[str]] = None,
                 url_redirect_title: Optional[pulumi.Input[str]] = None,
                 url_redirect_type: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        ## # Resource: NameserverRecord

        Provides a INWX nameserver record resource

        ## Example Usage

        ```python
        import pulumi
        import pulumi_inwx as inwx

        example_com_txt1 = inwx.NameserverRecord("exampleComTxt1",
            content="DNS records with terraform",
            domain="example.com",
            type="TXT")
        ```

        ## Import

        INWX nameserver records can be imported using the `id`, e.g.,

        ```sh
         $ pulumi import inwx:index/nameserverRecord:NameserverRecord inwx_nameserver_record example.com:2147483647
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] content: Content of the nameserver record
        :param pulumi.Input[str] domain: Name of the domain
        :param pulumi.Input[str] name: Name of the nameserver record
        :param pulumi.Input[int] prio: Priority of the nameserver record. Default: `0`
        :param pulumi.Input[int] ro_id: DNS domain id
        :param pulumi.Input[bool] testing: Execute command in testing mode. Default: `false`
        :param pulumi.Input[int] ttl: TTL (time to live) of the nameserver record. Default: `3600`
        :param pulumi.Input[str] type: Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
               `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
               `URI`, `URL`
        :param pulumi.Input[bool] url_append: Append the path for redirection. Default: `false`
        :param pulumi.Input[str] url_redirect_description: Description of the frame redirection
        :param pulumi.Input[str] url_redirect_fav_icon: FavIcon of the frame redirection
        :param pulumi.Input[str] url_redirect_keywords: Keywords of the frame redirection
        :param pulumi.Input[str] url_redirect_title: Title of the frame redirection
        :param pulumi.Input[str] url_redirect_type: Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: NameserverRecordArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## # Resource: NameserverRecord

        Provides a INWX nameserver record resource

        ## Example Usage

        ```python
        import pulumi
        import pulumi_inwx as inwx

        example_com_txt1 = inwx.NameserverRecord("exampleComTxt1",
            content="DNS records with terraform",
            domain="example.com",
            type="TXT")
        ```

        ## Import

        INWX nameserver records can be imported using the `id`, e.g.,

        ```sh
         $ pulumi import inwx:index/nameserverRecord:NameserverRecord inwx_nameserver_record example.com:2147483647
        ```

        :param str resource_name: The name of the resource.
        :param NameserverRecordArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(NameserverRecordArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 content: Optional[pulumi.Input[str]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 prio: Optional[pulumi.Input[int]] = None,
                 ro_id: Optional[pulumi.Input[int]] = None,
                 testing: Optional[pulumi.Input[bool]] = None,
                 ttl: Optional[pulumi.Input[int]] = None,
                 type: Optional[pulumi.Input[str]] = None,
                 url_append: Optional[pulumi.Input[bool]] = None,
                 url_redirect_description: Optional[pulumi.Input[str]] = None,
                 url_redirect_fav_icon: Optional[pulumi.Input[str]] = None,
                 url_redirect_keywords: Optional[pulumi.Input[str]] = None,
                 url_redirect_title: Optional[pulumi.Input[str]] = None,
                 url_redirect_type: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = NameserverRecordArgs.__new__(NameserverRecordArgs)

            if content is None and not opts.urn:
                raise TypeError("Missing required property 'content'")
            __props__.__dict__["content"] = content
            if domain is None and not opts.urn:
                raise TypeError("Missing required property 'domain'")
            __props__.__dict__["domain"] = domain
            __props__.__dict__["name"] = name
            __props__.__dict__["prio"] = prio
            __props__.__dict__["ro_id"] = ro_id
            __props__.__dict__["testing"] = testing
            __props__.__dict__["ttl"] = ttl
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["url_append"] = url_append
            __props__.__dict__["url_redirect_description"] = url_redirect_description
            __props__.__dict__["url_redirect_fav_icon"] = url_redirect_fav_icon
            __props__.__dict__["url_redirect_keywords"] = url_redirect_keywords
            __props__.__dict__["url_redirect_title"] = url_redirect_title
            __props__.__dict__["url_redirect_type"] = url_redirect_type
        super(NameserverRecord, __self__).__init__(
            'inwx:index/nameserverRecord:NameserverRecord',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            content: Optional[pulumi.Input[str]] = None,
            domain: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            prio: Optional[pulumi.Input[int]] = None,
            ro_id: Optional[pulumi.Input[int]] = None,
            testing: Optional[pulumi.Input[bool]] = None,
            ttl: Optional[pulumi.Input[int]] = None,
            type: Optional[pulumi.Input[str]] = None,
            url_append: Optional[pulumi.Input[bool]] = None,
            url_redirect_description: Optional[pulumi.Input[str]] = None,
            url_redirect_fav_icon: Optional[pulumi.Input[str]] = None,
            url_redirect_keywords: Optional[pulumi.Input[str]] = None,
            url_redirect_title: Optional[pulumi.Input[str]] = None,
            url_redirect_type: Optional[pulumi.Input[str]] = None) -> 'NameserverRecord':
        """
        Get an existing NameserverRecord resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] content: Content of the nameserver record
        :param pulumi.Input[str] domain: Name of the domain
        :param pulumi.Input[str] name: Name of the nameserver record
        :param pulumi.Input[int] prio: Priority of the nameserver record. Default: `0`
        :param pulumi.Input[int] ro_id: DNS domain id
        :param pulumi.Input[bool] testing: Execute command in testing mode. Default: `false`
        :param pulumi.Input[int] ttl: TTL (time to live) of the nameserver record. Default: `3600`
        :param pulumi.Input[str] type: Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
               `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
               `URI`, `URL`
        :param pulumi.Input[bool] url_append: Append the path for redirection. Default: `false`
        :param pulumi.Input[str] url_redirect_description: Description of the frame redirection
        :param pulumi.Input[str] url_redirect_fav_icon: FavIcon of the frame redirection
        :param pulumi.Input[str] url_redirect_keywords: Keywords of the frame redirection
        :param pulumi.Input[str] url_redirect_title: Title of the frame redirection
        :param pulumi.Input[str] url_redirect_type: Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _NameserverRecordState.__new__(_NameserverRecordState)

        __props__.__dict__["content"] = content
        __props__.__dict__["domain"] = domain
        __props__.__dict__["name"] = name
        __props__.__dict__["prio"] = prio
        __props__.__dict__["ro_id"] = ro_id
        __props__.__dict__["testing"] = testing
        __props__.__dict__["ttl"] = ttl
        __props__.__dict__["type"] = type
        __props__.__dict__["url_append"] = url_append
        __props__.__dict__["url_redirect_description"] = url_redirect_description
        __props__.__dict__["url_redirect_fav_icon"] = url_redirect_fav_icon
        __props__.__dict__["url_redirect_keywords"] = url_redirect_keywords
        __props__.__dict__["url_redirect_title"] = url_redirect_title
        __props__.__dict__["url_redirect_type"] = url_redirect_type
        return NameserverRecord(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def content(self) -> pulumi.Output[str]:
        """
        Content of the nameserver record
        """
        return pulumi.get(self, "content")

    @property
    @pulumi.getter
    def domain(self) -> pulumi.Output[str]:
        """
        Name of the domain
        """
        return pulumi.get(self, "domain")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        Name of the nameserver record
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def prio(self) -> pulumi.Output[Optional[int]]:
        """
        Priority of the nameserver record. Default: `0`
        """
        return pulumi.get(self, "prio")

    @property
    @pulumi.getter(name="roId")
    def ro_id(self) -> pulumi.Output[Optional[int]]:
        """
        DNS domain id
        """
        return pulumi.get(self, "ro_id")

    @property
    @pulumi.getter
    def testing(self) -> pulumi.Output[Optional[bool]]:
        """
        Execute command in testing mode. Default: `false`
        """
        return pulumi.get(self, "testing")

    @property
    @pulumi.getter
    def ttl(self) -> pulumi.Output[Optional[int]]:
        """
        TTL (time to live) of the nameserver record. Default: `3600`
        """
        return pulumi.get(self, "ttl")

    @property
    @pulumi.getter
    def type(self) -> pulumi.Output[str]:
        """
        Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
        `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
        `URI`, `URL`
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter(name="urlAppend")
    def url_append(self) -> pulumi.Output[Optional[bool]]:
        """
        Append the path for redirection. Default: `false`
        """
        return pulumi.get(self, "url_append")

    @property
    @pulumi.getter(name="urlRedirectDescription")
    def url_redirect_description(self) -> pulumi.Output[Optional[str]]:
        """
        Description of the frame redirection
        """
        return pulumi.get(self, "url_redirect_description")

    @property
    @pulumi.getter(name="urlRedirectFavIcon")
    def url_redirect_fav_icon(self) -> pulumi.Output[Optional[str]]:
        """
        FavIcon of the frame redirection
        """
        return pulumi.get(self, "url_redirect_fav_icon")

    @property
    @pulumi.getter(name="urlRedirectKeywords")
    def url_redirect_keywords(self) -> pulumi.Output[Optional[str]]:
        """
        Keywords of the frame redirection
        """
        return pulumi.get(self, "url_redirect_keywords")

    @property
    @pulumi.getter(name="urlRedirectTitle")
    def url_redirect_title(self) -> pulumi.Output[Optional[str]]:
        """
        Title of the frame redirection
        """
        return pulumi.get(self, "url_redirect_title")

    @property
    @pulumi.getter(name="urlRedirectType")
    def url_redirect_type(self) -> pulumi.Output[Optional[str]]:
        """
        Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
        """
        return pulumi.get(self, "url_redirect_type")

