# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'DomainContacts',
]

@pulumi.output_type
class DomainContacts(dict):
    def __init__(__self__, *,
                 admin: int,
                 billing: int,
                 registrant: int,
                 tech: int):
        """
        :param int admin: Id of the admin contact
        :param int billing: Id of the billing contact
        :param int registrant: Id of the registrant contact
        :param int tech: Id of the tech contact
        """
        pulumi.set(__self__, "admin", admin)
        pulumi.set(__self__, "billing", billing)
        pulumi.set(__self__, "registrant", registrant)
        pulumi.set(__self__, "tech", tech)

    @property
    @pulumi.getter
    def admin(self) -> int:
        """
        Id of the admin contact
        """
        return pulumi.get(self, "admin")

    @property
    @pulumi.getter
    def billing(self) -> int:
        """
        Id of the billing contact
        """
        return pulumi.get(self, "billing")

    @property
    @pulumi.getter
    def registrant(self) -> int:
        """
        Id of the registrant contact
        """
        return pulumi.get(self, "registrant")

    @property
    @pulumi.getter
    def tech(self) -> int:
        """
        Id of the tech contact
        """
        return pulumi.get(self, "tech")


