# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 password: pulumi.Input[str],
                 username: pulumi.Input[str],
                 api_url: Optional[pulumi.Input[str]] = None,
                 tan: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a Provider resource.
        :param pulumi.Input[str] password: Login password of the api
        :param pulumi.Input[str] username: Login username of the api
        :param pulumi.Input[str] api_url: URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
               `https://api.ote.domrobot.com/jsonrpc/` for tests
        :param pulumi.Input[str] tan: Mobile-TAN to unlock account
        """
        pulumi.set(__self__, "password", password)
        pulumi.set(__self__, "username", username)
        if api_url is not None:
            pulumi.set(__self__, "api_url", api_url)
        if tan is not None:
            pulumi.set(__self__, "tan", tan)

    @property
    @pulumi.getter
    def password(self) -> pulumi.Input[str]:
        """
        Login password of the api
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[str]):
        pulumi.set(self, "password", value)

    @property
    @pulumi.getter
    def username(self) -> pulumi.Input[str]:
        """
        Login username of the api
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: pulumi.Input[str]):
        pulumi.set(self, "username", value)

    @property
    @pulumi.getter(name="apiUrl")
    def api_url(self) -> Optional[pulumi.Input[str]]:
        """
        URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
        `https://api.ote.domrobot.com/jsonrpc/` for tests
        """
        return pulumi.get(self, "api_url")

    @api_url.setter
    def api_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "api_url", value)

    @property
    @pulumi.getter
    def tan(self) -> Optional[pulumi.Input[str]]:
        """
        Mobile-TAN to unlock account
        """
        return pulumi.get(self, "tan")

    @tan.setter
    def tan(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "tan", value)


class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_url: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[str]] = None,
                 tan: Optional[pulumi.Input[str]] = None,
                 username: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        The provider type for the inwx package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] api_url: URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
               `https://api.ote.domrobot.com/jsonrpc/` for tests
        :param pulumi.Input[str] password: Login password of the api
        :param pulumi.Input[str] tan: Mobile-TAN to unlock account
        :param pulumi.Input[str] username: Login username of the api
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProviderArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The provider type for the inwx package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_url: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[str]] = None,
                 tan: Optional[pulumi.Input[str]] = None,
                 username: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            __props__.__dict__["api_url"] = api_url
            if password is None and not opts.urn:
                raise TypeError("Missing required property 'password'")
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["tan"] = None if tan is None else pulumi.Output.secret(tan)
            if username is None and not opts.urn:
                raise TypeError("Missing required property 'username'")
            __props__.__dict__["username"] = None if username is None else pulumi.Output.secret(username)
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["password", "tan", "username"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'inwx',
            resource_name,
            __props__,
            opts)

    @property
    @pulumi.getter(name="apiUrl")
    def api_url(self) -> pulumi.Output[Optional[str]]:
        """
        URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
        `https://api.ote.domrobot.com/jsonrpc/` for tests
        """
        return pulumi.get(self, "api_url")

    @property
    @pulumi.getter
    def password(self) -> pulumi.Output[str]:
        """
        Login password of the api
        """
        return pulumi.get(self, "password")

    @property
    @pulumi.getter
    def tan(self) -> pulumi.Output[Optional[str]]:
        """
        Mobile-TAN to unlock account
        """
        return pulumi.get(self, "tan")

    @property
    @pulumi.getter
    def username(self) -> pulumi.Output[str]:
        """
        Login username of the api
        """
        return pulumi.get(self, "username")

