// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/wombelix/pulumi-inwx/sdk/go/inwx/internal"
)

var _ = internal.GetEnvOrDefault

// URL of the RPC API endpoint. Use `https://api.domrobot.com/jsonrpc/` for production and
// `https://api.ote.domrobot.com/jsonrpc/` for tests
func GetApiUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "inwx:apiUrl")
}

// Login password of the api
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "inwx:password")
}

// Mobile-TAN to unlock account
func GetTan(ctx *pulumi.Context) string {
	return config.Get(ctx, "inwx:tan")
}

// Login username of the api
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "inwx:username")
}
