// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DomainContacts {
    /**
     * Id of the admin contact
     */
    admin: pulumi.Input<number>;
    /**
     * Id of the billing contact
     */
    billing: pulumi.Input<number>;
    /**
     * Id of the registrant contact
     */
    registrant: pulumi.Input<number>;
    /**
     * Id of the tech contact
     */
    tech: pulumi.Input<number>;
}
