// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Inwx.Inputs
{

    public sealed class DomainContactsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Id of the admin contact
        /// </summary>
        [Input("admin", required: true)]
        public Input<int> Admin { get; set; } = null!;

        /// <summary>
        /// Id of the billing contact
        /// </summary>
        [Input("billing", required: true)]
        public Input<int> Billing { get; set; } = null!;

        /// <summary>
        /// Id of the registrant contact
        /// </summary>
        [Input("registrant", required: true)]
        public Input<int> Registrant { get; set; } = null!;

        /// <summary>
        /// Id of the tech contact
        /// </summary>
        [Input("tech", required: true)]
        public Input<int> Tech { get; set; } = null!;

        public DomainContactsArgs()
        {
        }
        public static new DomainContactsArgs Empty => new DomainContactsArgs();
    }
}
