// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Resource: inwx.DnssecKey
 *
 * Provides a INWX DNSSEC key resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as inwx from "@pulumi/inwx";
 *
 * const exampleCom = new inwx.DnssecKey("exampleCom", {
 *     algorithm: "SHA256",
 *     domain: "example.com",
 *     publicKey: "ac12c2...",
 * });
 * ```
 * ## Caveats
 *
 * ### Nameservers
 *
 * Can not be used in conjunction with INWX nameservers.
 *
 * ## Import
 *
 * INWX DNSSEC keys can be imported using the domain name and digest e.g.,
 *
 * ```sh
 *  $ pulumi import inwx:index/dnssecKey:DnssecKey example_com example.com/4E1243BD22C66E76C2BA9EDDC1F91394E57F9F83
 * ```
 */
export class DnssecKey extends pulumi.CustomResource {
    /**
     * Get an existing DnssecKey resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnssecKeyState, opts?: pulumi.CustomResourceOptions): DnssecKey {
        return new DnssecKey(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'inwx:index/dnssecKey:DnssecKey';

    /**
     * Returns true if the given object is an instance of DnssecKey.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnssecKey {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnssecKey.__pulumiType;
    }

    /**
     * Algorithm used for the public key
     */
    public readonly algorithm!: pulumi.Output<number>;
    /**
     * Computed digest for the public key
     */
    public /*out*/ readonly digest!: pulumi.Output<string>;
    /**
     * Digest type
     */
    public /*out*/ readonly digestType!: pulumi.Output<number>;
    /**
     * Name of the domain
     */
    public readonly domain!: pulumi.Output<string>;
    /**
     * Key flag (256=ZSK, 257=KSK)
     */
    public /*out*/ readonly flag!: pulumi.Output<number>;
    /**
     * Key tag
     */
    public /*out*/ readonly keyTag!: pulumi.Output<number>;
    /**
     * Public key of the domain
     */
    public readonly publicKey!: pulumi.Output<string>;
    /**
     * DNSSEC status
     */
    public /*out*/ readonly status!: pulumi.Output<string>;

    /**
     * Create a DnssecKey resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnssecKeyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnssecKeyArgs | DnssecKeyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnssecKeyState | undefined;
            resourceInputs["algorithm"] = state ? state.algorithm : undefined;
            resourceInputs["digest"] = state ? state.digest : undefined;
            resourceInputs["digestType"] = state ? state.digestType : undefined;
            resourceInputs["domain"] = state ? state.domain : undefined;
            resourceInputs["flag"] = state ? state.flag : undefined;
            resourceInputs["keyTag"] = state ? state.keyTag : undefined;
            resourceInputs["publicKey"] = state ? state.publicKey : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
        } else {
            const args = argsOrState as DnssecKeyArgs | undefined;
            if ((!args || args.algorithm === undefined) && !opts.urn) {
                throw new Error("Missing required property 'algorithm'");
            }
            if ((!args || args.domain === undefined) && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if ((!args || args.publicKey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'publicKey'");
            }
            resourceInputs["algorithm"] = args ? args.algorithm : undefined;
            resourceInputs["domain"] = args ? args.domain : undefined;
            resourceInputs["publicKey"] = args ? args.publicKey : undefined;
            resourceInputs["digest"] = undefined /*out*/;
            resourceInputs["digestType"] = undefined /*out*/;
            resourceInputs["flag"] = undefined /*out*/;
            resourceInputs["keyTag"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnssecKey.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DnssecKey resources.
 */
export interface DnssecKeyState {
    /**
     * Algorithm used for the public key
     */
    algorithm?: pulumi.Input<number>;
    /**
     * Computed digest for the public key
     */
    digest?: pulumi.Input<string>;
    /**
     * Digest type
     */
    digestType?: pulumi.Input<number>;
    /**
     * Name of the domain
     */
    domain?: pulumi.Input<string>;
    /**
     * Key flag (256=ZSK, 257=KSK)
     */
    flag?: pulumi.Input<number>;
    /**
     * Key tag
     */
    keyTag?: pulumi.Input<number>;
    /**
     * Public key of the domain
     */
    publicKey?: pulumi.Input<string>;
    /**
     * DNSSEC status
     */
    status?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DnssecKey resource.
 */
export interface DnssecKeyArgs {
    /**
     * Algorithm used for the public key
     */
    algorithm: pulumi.Input<number>;
    /**
     * Name of the domain
     */
    domain: pulumi.Input<string>;
    /**
     * Public key of the domain
     */
    publicKey: pulumi.Input<string>;
}
