// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Import
 *
 * INWX Domains can be imported using the domain name, e.g.,
 *
 * ```sh
 *  $ pulumi import inwx:index/domain:Domain example_com "example.com"
 * ```
 */
export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainState, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'inwx:index/domain:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    /**
     * Contacts of the domain
     */
    public readonly contacts!: pulumi.Output<outputs.DomainContacts>;
    /**
     * Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
     */
    public readonly extraData!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Name of the domain
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Set of nameservers of the domain. Min Items: 1
     */
    public readonly nameservers!: pulumi.Output<string[] | undefined>;
    /**
     * Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
     */
    public readonly period!: pulumi.Output<string>;
    /**
     * Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
     */
    public readonly renewalMode!: pulumi.Output<string | undefined>;
    /**
     * Whether the domain transfer lock should be enabled. Default: `true`
     */
    public readonly transferLock!: pulumi.Output<boolean | undefined>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainArgs | DomainState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DomainState | undefined;
            resourceInputs["contacts"] = state ? state.contacts : undefined;
            resourceInputs["extraData"] = state ? state.extraData : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["nameservers"] = state ? state.nameservers : undefined;
            resourceInputs["period"] = state ? state.period : undefined;
            resourceInputs["renewalMode"] = state ? state.renewalMode : undefined;
            resourceInputs["transferLock"] = state ? state.transferLock : undefined;
        } else {
            const args = argsOrState as DomainArgs | undefined;
            if ((!args || args.contacts === undefined) && !opts.urn) {
                throw new Error("Missing required property 'contacts'");
            }
            if ((!args || args.period === undefined) && !opts.urn) {
                throw new Error("Missing required property 'period'");
            }
            resourceInputs["contacts"] = args ? args.contacts : undefined;
            resourceInputs["extraData"] = args ? args.extraData : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["nameservers"] = args ? args.nameservers : undefined;
            resourceInputs["period"] = args ? args.period : undefined;
            resourceInputs["renewalMode"] = args ? args.renewalMode : undefined;
            resourceInputs["transferLock"] = args ? args.transferLock : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Domain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Domain resources.
 */
export interface DomainState {
    /**
     * Contacts of the domain
     */
    contacts?: pulumi.Input<inputs.DomainContacts>;
    /**
     * Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
     */
    extraData?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Name of the domain
     */
    name?: pulumi.Input<string>;
    /**
     * Set of nameservers of the domain. Min Items: 1
     */
    nameservers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
     */
    period?: pulumi.Input<string>;
    /**
     * Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
     */
    renewalMode?: pulumi.Input<string>;
    /**
     * Whether the domain transfer lock should be enabled. Default: `true`
     */
    transferLock?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    /**
     * Contacts of the domain
     */
    contacts: pulumi.Input<inputs.DomainContacts>;
    /**
     * Extra data, needed for some jurisdictions. Valid extra data types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.extdata
     */
    extraData?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Name of the domain
     */
    name?: pulumi.Input<string>;
    /**
     * Set of nameservers of the domain. Min Items: 1
     */
    nameservers?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Registration period of the domain. Valid types: https://www.inwx.de/en/help/apidoc/f/ch03.html#type.period
     */
    period: pulumi.Input<string>;
    /**
     * Renewal mode of the domain. One of: `AUTORENEW`, `AUTODELETE`, `AUTOEXPIRE`. Default: `AUTORENEW`
     */
    renewalMode?: pulumi.Input<string>;
    /**
     * Whether the domain transfer lock should be enabled. Default: `true`
     */
    transferLock?: pulumi.Input<boolean>;
}
