// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Resource: inwx.DomainContact
 *
 * Provides a INWX domain contact resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as inwx from "@pulumi/inwx";
 *
 * const examplePerson = new inwx.DomainContact("examplePerson", {
 *     city: "Example City",
 *     countryCode: "EX",
 *     email: "person@example.invalid",
 *     phoneNumber: "+00.00000000000",
 *     postalCode: "0",
 *     stateProvince: "Example State",
 *     streetAddress: "Example Street 0",
 *     type: "PERSON",
 * });
 * ```
 *
 * ## Import
 *
 * INWX domain contacts can be imported using the `id`, e.g.,
 *
 * ```sh
 *  $ pulumi import inwx:index/domainContact:DomainContact inwx_domain_contact 2147483647
 * ```
 */
export class DomainContact extends pulumi.CustomResource {
    /**
     * Get an existing DomainContact resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainContactState, opts?: pulumi.CustomResourceOptions): DomainContact {
        return new DomainContact(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'inwx:index/domainContact:DomainContact';

    /**
     * Returns true if the given object is an instance of DomainContact.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DomainContact {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DomainContact.__pulumiType;
    }

    /**
     * City of the contact
     */
    public readonly city!: pulumi.Output<string>;
    /**
     * Country code of the contact. Must be two characters
     */
    public readonly countryCode!: pulumi.Output<string>;
    /**
     * Contact email address
     */
    public readonly email!: pulumi.Output<string>;
    /**
     * Fax number of the contact
     */
    public readonly fax!: pulumi.Output<string | undefined>;
    /**
     * First and lastname of the contact
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The legal name of the organization. Required for types other than person
     */
    public readonly organization!: pulumi.Output<string | undefined>;
    /**
     * Phone number of the contact
     */
    public readonly phoneNumber!: pulumi.Output<string>;
    /**
     * Postal Code/Zipcode of the contact
     */
    public readonly postalCode!: pulumi.Output<string>;
    /**
     * Custom description of the contact
     */
    public readonly remarks!: pulumi.Output<string | undefined>;
    /**
     * State/Province name of the contact
     */
    public readonly stateProvince!: pulumi.Output<string | undefined>;
    /**
     * Street Address of the contact
     */
    public readonly streetAddress!: pulumi.Output<string>;
    /**
     * Type of contact. One of: `ORG`, `PERSON`, `ROLE`
     */
    public readonly type!: pulumi.Output<string>;
    /**
     * Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
     */
    public readonly whoisProtection!: pulumi.Output<boolean | undefined>;

    /**
     * Create a DomainContact resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainContactArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainContactArgs | DomainContactState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DomainContactState | undefined;
            resourceInputs["city"] = state ? state.city : undefined;
            resourceInputs["countryCode"] = state ? state.countryCode : undefined;
            resourceInputs["email"] = state ? state.email : undefined;
            resourceInputs["fax"] = state ? state.fax : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["organization"] = state ? state.organization : undefined;
            resourceInputs["phoneNumber"] = state ? state.phoneNumber : undefined;
            resourceInputs["postalCode"] = state ? state.postalCode : undefined;
            resourceInputs["remarks"] = state ? state.remarks : undefined;
            resourceInputs["stateProvince"] = state ? state.stateProvince : undefined;
            resourceInputs["streetAddress"] = state ? state.streetAddress : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
            resourceInputs["whoisProtection"] = state ? state.whoisProtection : undefined;
        } else {
            const args = argsOrState as DomainContactArgs | undefined;
            if ((!args || args.city === undefined) && !opts.urn) {
                throw new Error("Missing required property 'city'");
            }
            if ((!args || args.countryCode === undefined) && !opts.urn) {
                throw new Error("Missing required property 'countryCode'");
            }
            if ((!args || args.email === undefined) && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if ((!args || args.phoneNumber === undefined) && !opts.urn) {
                throw new Error("Missing required property 'phoneNumber'");
            }
            if ((!args || args.postalCode === undefined) && !opts.urn) {
                throw new Error("Missing required property 'postalCode'");
            }
            if ((!args || args.streetAddress === undefined) && !opts.urn) {
                throw new Error("Missing required property 'streetAddress'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["city"] = args ? args.city : undefined;
            resourceInputs["countryCode"] = args ? args.countryCode : undefined;
            resourceInputs["email"] = args ? args.email : undefined;
            resourceInputs["fax"] = args ? args.fax : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["organization"] = args ? args.organization : undefined;
            resourceInputs["phoneNumber"] = args ? args.phoneNumber : undefined;
            resourceInputs["postalCode"] = args ? args.postalCode : undefined;
            resourceInputs["remarks"] = args ? args.remarks : undefined;
            resourceInputs["stateProvince"] = args ? args.stateProvince : undefined;
            resourceInputs["streetAddress"] = args ? args.streetAddress : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["whoisProtection"] = args ? args.whoisProtection : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DomainContact.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DomainContact resources.
 */
export interface DomainContactState {
    /**
     * City of the contact
     */
    city?: pulumi.Input<string>;
    /**
     * Country code of the contact. Must be two characters
     */
    countryCode?: pulumi.Input<string>;
    /**
     * Contact email address
     */
    email?: pulumi.Input<string>;
    /**
     * Fax number of the contact
     */
    fax?: pulumi.Input<string>;
    /**
     * First and lastname of the contact
     */
    name?: pulumi.Input<string>;
    /**
     * The legal name of the organization. Required for types other than person
     */
    organization?: pulumi.Input<string>;
    /**
     * Phone number of the contact
     */
    phoneNumber?: pulumi.Input<string>;
    /**
     * Postal Code/Zipcode of the contact
     */
    postalCode?: pulumi.Input<string>;
    /**
     * Custom description of the contact
     */
    remarks?: pulumi.Input<string>;
    /**
     * State/Province name of the contact
     */
    stateProvince?: pulumi.Input<string>;
    /**
     * Street Address of the contact
     */
    streetAddress?: pulumi.Input<string>;
    /**
     * Type of contact. One of: `ORG`, `PERSON`, `ROLE`
     */
    type?: pulumi.Input<string>;
    /**
     * Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
     */
    whoisProtection?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a DomainContact resource.
 */
export interface DomainContactArgs {
    /**
     * City of the contact
     */
    city: pulumi.Input<string>;
    /**
     * Country code of the contact. Must be two characters
     */
    countryCode: pulumi.Input<string>;
    /**
     * Contact email address
     */
    email: pulumi.Input<string>;
    /**
     * Fax number of the contact
     */
    fax?: pulumi.Input<string>;
    /**
     * First and lastname of the contact
     */
    name?: pulumi.Input<string>;
    /**
     * The legal name of the organization. Required for types other than person
     */
    organization?: pulumi.Input<string>;
    /**
     * Phone number of the contact
     */
    phoneNumber: pulumi.Input<string>;
    /**
     * Postal Code/Zipcode of the contact
     */
    postalCode: pulumi.Input<string>;
    /**
     * Custom description of the contact
     */
    remarks?: pulumi.Input<string>;
    /**
     * State/Province name of the contact
     */
    stateProvince?: pulumi.Input<string>;
    /**
     * Street Address of the contact
     */
    streetAddress: pulumi.Input<string>;
    /**
     * Type of contact. One of: `ORG`, `PERSON`, `ROLE`
     */
    type: pulumi.Input<string>;
    /**
     * Whether whois protection for the contact should be enabled. Depends on the registry supporting it. Not the same as whois protection for a domain
     */
    whoisProtection?: pulumi.Input<boolean>;
}
