// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { DnssecKeyArgs, DnssecKeyState } from "./dnssecKey";
export type DnssecKey = import("./dnssecKey").DnssecKey;
export const DnssecKey: typeof import("./dnssecKey").DnssecKey = null as any;
utilities.lazyLoad(exports, ["DnssecKey"], () => require("./dnssecKey"));

export { DomainArgs, DomainState } from "./domain";
export type Domain = import("./domain").Domain;
export const Domain: typeof import("./domain").Domain = null as any;
utilities.lazyLoad(exports, ["Domain"], () => require("./domain"));

export { DomainContactArgs, DomainContactState } from "./domainContact";
export type DomainContact = import("./domainContact").DomainContact;
export const DomainContact: typeof import("./domainContact").DomainContact = null as any;
utilities.lazyLoad(exports, ["DomainContact"], () => require("./domainContact"));

export { NameserverRecordArgs, NameserverRecordState } from "./nameserverRecord";
export type NameserverRecord = import("./nameserverRecord").NameserverRecord;
export const NameserverRecord: typeof import("./nameserverRecord").NameserverRecord = null as any;
utilities.lazyLoad(exports, ["NameserverRecord"], () => require("./nameserverRecord"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "inwx:index/dnssecKey:DnssecKey":
                return new DnssecKey(name, <any>undefined, { urn })
            case "inwx:index/domain:Domain":
                return new Domain(name, <any>undefined, { urn })
            case "inwx:index/domainContact:DomainContact":
                return new DomainContact(name, <any>undefined, { urn })
            case "inwx:index/nameserverRecord:NameserverRecord":
                return new NameserverRecord(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("inwx", "index/dnssecKey", _module)
pulumi.runtime.registerResourceModule("inwx", "index/domain", _module)
pulumi.runtime.registerResourceModule("inwx", "index/domainContact", _module)
pulumi.runtime.registerResourceModule("inwx", "index/nameserverRecord", _module)
pulumi.runtime.registerResourcePackage("inwx", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:inwx") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
