// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Resource: inwx.NameserverRecord
 *
 * Provides a INWX nameserver record resource
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as inwx from "@pulumi/inwx";
 *
 * const exampleComTxt1 = new inwx.NameserverRecord("exampleComTxt1", {
 *     content: "DNS records with terraform",
 *     domain: "example.com",
 *     type: "TXT",
 * });
 * ```
 *
 * ## Import
 *
 * INWX nameserver records can be imported using the `id`, e.g.,
 *
 * ```sh
 *  $ pulumi import inwx:index/nameserverRecord:NameserverRecord inwx_nameserver_record example.com:2147483647
 * ```
 */
export class NameserverRecord extends pulumi.CustomResource {
    /**
     * Get an existing NameserverRecord resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NameserverRecordState, opts?: pulumi.CustomResourceOptions): NameserverRecord {
        return new NameserverRecord(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'inwx:index/nameserverRecord:NameserverRecord';

    /**
     * Returns true if the given object is an instance of NameserverRecord.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NameserverRecord {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NameserverRecord.__pulumiType;
    }

    /**
     * Content of the nameserver record
     */
    public readonly content!: pulumi.Output<string>;
    /**
     * Name of the domain
     */
    public readonly domain!: pulumi.Output<string>;
    /**
     * Name of the nameserver record
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Priority of the nameserver record. Default: `0`
     */
    public readonly prio!: pulumi.Output<number | undefined>;
    /**
     * DNS domain id
     */
    public readonly roId!: pulumi.Output<number | undefined>;
    /**
     * Execute command in testing mode. Default: `false`
     */
    public readonly testing!: pulumi.Output<boolean | undefined>;
    /**
     * TTL (time to live) of the nameserver record. Default: `3600`
     */
    public readonly ttl!: pulumi.Output<number | undefined>;
    /**
     * Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
     * `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
     * `URI`, `URL`
     */
    public readonly type!: pulumi.Output<string>;
    /**
     * Append the path for redirection. Default: `false`
     */
    public readonly urlAppend!: pulumi.Output<boolean | undefined>;
    /**
     * Description of the frame redirection
     */
    public readonly urlRedirectDescription!: pulumi.Output<string | undefined>;
    /**
     * FavIcon of the frame redirection
     */
    public readonly urlRedirectFavIcon!: pulumi.Output<string | undefined>;
    /**
     * Keywords of the frame redirection
     */
    public readonly urlRedirectKeywords!: pulumi.Output<string | undefined>;
    /**
     * Title of the frame redirection
     */
    public readonly urlRedirectTitle!: pulumi.Output<string | undefined>;
    /**
     * Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
     */
    public readonly urlRedirectType!: pulumi.Output<string | undefined>;

    /**
     * Create a NameserverRecord resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NameserverRecordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NameserverRecordArgs | NameserverRecordState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NameserverRecordState | undefined;
            resourceInputs["content"] = state ? state.content : undefined;
            resourceInputs["domain"] = state ? state.domain : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["prio"] = state ? state.prio : undefined;
            resourceInputs["roId"] = state ? state.roId : undefined;
            resourceInputs["testing"] = state ? state.testing : undefined;
            resourceInputs["ttl"] = state ? state.ttl : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
            resourceInputs["urlAppend"] = state ? state.urlAppend : undefined;
            resourceInputs["urlRedirectDescription"] = state ? state.urlRedirectDescription : undefined;
            resourceInputs["urlRedirectFavIcon"] = state ? state.urlRedirectFavIcon : undefined;
            resourceInputs["urlRedirectKeywords"] = state ? state.urlRedirectKeywords : undefined;
            resourceInputs["urlRedirectTitle"] = state ? state.urlRedirectTitle : undefined;
            resourceInputs["urlRedirectType"] = state ? state.urlRedirectType : undefined;
        } else {
            const args = argsOrState as NameserverRecordArgs | undefined;
            if ((!args || args.content === undefined) && !opts.urn) {
                throw new Error("Missing required property 'content'");
            }
            if ((!args || args.domain === undefined) && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["content"] = args ? args.content : undefined;
            resourceInputs["domain"] = args ? args.domain : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["prio"] = args ? args.prio : undefined;
            resourceInputs["roId"] = args ? args.roId : undefined;
            resourceInputs["testing"] = args ? args.testing : undefined;
            resourceInputs["ttl"] = args ? args.ttl : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["urlAppend"] = args ? args.urlAppend : undefined;
            resourceInputs["urlRedirectDescription"] = args ? args.urlRedirectDescription : undefined;
            resourceInputs["urlRedirectFavIcon"] = args ? args.urlRedirectFavIcon : undefined;
            resourceInputs["urlRedirectKeywords"] = args ? args.urlRedirectKeywords : undefined;
            resourceInputs["urlRedirectTitle"] = args ? args.urlRedirectTitle : undefined;
            resourceInputs["urlRedirectType"] = args ? args.urlRedirectType : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NameserverRecord.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NameserverRecord resources.
 */
export interface NameserverRecordState {
    /**
     * Content of the nameserver record
     */
    content?: pulumi.Input<string>;
    /**
     * Name of the domain
     */
    domain?: pulumi.Input<string>;
    /**
     * Name of the nameserver record
     */
    name?: pulumi.Input<string>;
    /**
     * Priority of the nameserver record. Default: `0`
     */
    prio?: pulumi.Input<number>;
    /**
     * DNS domain id
     */
    roId?: pulumi.Input<number>;
    /**
     * Execute command in testing mode. Default: `false`
     */
    testing?: pulumi.Input<boolean>;
    /**
     * TTL (time to live) of the nameserver record. Default: `3600`
     */
    ttl?: pulumi.Input<number>;
    /**
     * Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
     * `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
     * `URI`, `URL`
     */
    type?: pulumi.Input<string>;
    /**
     * Append the path for redirection. Default: `false`
     */
    urlAppend?: pulumi.Input<boolean>;
    /**
     * Description of the frame redirection
     */
    urlRedirectDescription?: pulumi.Input<string>;
    /**
     * FavIcon of the frame redirection
     */
    urlRedirectFavIcon?: pulumi.Input<string>;
    /**
     * Keywords of the frame redirection
     */
    urlRedirectKeywords?: pulumi.Input<string>;
    /**
     * Title of the frame redirection
     */
    urlRedirectTitle?: pulumi.Input<string>;
    /**
     * Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
     */
    urlRedirectType?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NameserverRecord resource.
 */
export interface NameserverRecordArgs {
    /**
     * Content of the nameserver record
     */
    content: pulumi.Input<string>;
    /**
     * Name of the domain
     */
    domain: pulumi.Input<string>;
    /**
     * Name of the nameserver record
     */
    name?: pulumi.Input<string>;
    /**
     * Priority of the nameserver record. Default: `0`
     */
    prio?: pulumi.Input<number>;
    /**
     * DNS domain id
     */
    roId?: pulumi.Input<number>;
    /**
     * Execute command in testing mode. Default: `false`
     */
    testing?: pulumi.Input<boolean>;
    /**
     * TTL (time to live) of the nameserver record. Default: `3600`
     */
    ttl?: pulumi.Input<number>;
    /**
     * Type of the nameserver record. One of: `A`, `AAAA`, `AFSDB`, `ALIAS`, `CAA`, `CERT`, `CNAME`, 
     * `HINFO`, `KEY`, `LOC`, `MX`, `NAPTR`, `NS`, `OPENPGPKEY`, `PTR`, `RP`, `SMIMEA`, `SOA`, `SRV`, `SSHFP`, `TLSA`, `TXT`,
     * `URI`, `URL`
     */
    type: pulumi.Input<string>;
    /**
     * Append the path for redirection. Default: `false`
     */
    urlAppend?: pulumi.Input<boolean>;
    /**
     * Description of the frame redirection
     */
    urlRedirectDescription?: pulumi.Input<string>;
    /**
     * FavIcon of the frame redirection
     */
    urlRedirectFavIcon?: pulumi.Input<string>;
    /**
     * Keywords of the frame redirection
     */
    urlRedirectKeywords?: pulumi.Input<string>;
    /**
     * Title of the frame redirection
     */
    urlRedirectTitle?: pulumi.Input<string>;
    /**
     * Type of the url redirection. One of: `HEADER301`, `HEADER302`, `FRAME`
     */
    urlRedirectType?: pulumi.Input<string>;
}
